### ISSUE TITLE
ndk-build failed

### ISSUE THREAD

**Issue by zyh001** [shadowsocksrr/shadowsocksr-android#1]
执行`sbt clean android:package-release`出现如下错误：
`[error] make: *** No rule to make target `jni/libancillary/fd_recv.c', needed by `obj/local/armeabi-v7a/objs/ancillary/libancillary/fd_recv.o'.  Stop.`
`[error] make: *** Waiting for unfinished jobs....`
`[error] Total time: 1 s, completed Aug 8, 2017 5:09:42 AM`

**Comment by zyh001** [comment]
执行 `git submodule update --init`但是依然报错希望指教一下

**Comment by Akkariiin** [comment]
环境？
是Linux吗？各库版本？

**Comment by zyh001** [comment]
@Akkariiin 
是Linux环境Ubuntu14.04
`java version "1.8.0_131"`
`sbt version 0.13.15`

**Comment by Akkariiin** [comment]
@zyh001 
ADK NDK版本呢

**Comment by zyh001** [comment]
@Akkariiin NDK：r15b
SDK：r24.4.1

**Comment by Akkariiin** [comment]
把NDK降到r12b
高版本编译的话，确定第三方库会出问题

https://developer.android.com/ndk/downloads/older_releases.html
这里下

**Comment by zyh001** [comment]
@Akkariiin 已降级，错误依旧
[info]Resolving org.scala-android#sbt-android;1.7.7 ...

[info] Resolving org.ow2.asm#asm-all;5.0.4 ...

[info] Resolving org.javassist#javassist;3.20.0-GA ...

[info] Resolving com.hanhuy.sbt#bintray-update-checker_2.10;0.2 ...

[info] Resolving org.scala-lang#scala-library;2.10.6 ...

[info] Resolving io.argonaut#argonaut_2.10;6.1a ...

[info] Resolving org.scalaz#scalaz-core_2.10;7.2.2 ...

[info] Resolving com.github.julien-truffaut#monocle-core_2.10;1.2.1 ...

[info] Resolving com.github.julien-truffaut#monocle-macro_2.10;1.2.1 ...

[info] Resolving org.scala-lang#scala-reflect;2.10.6 ...

[info] Resolving org.typelevel#macro-compat_2.10;1.1.0 ...

[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...

[info] Resolving com.android.tools.build#builder;2.2.0 ...

[info] Resolving com.android.tools.build#builder-model;2.2.0 ...

[info] Resolving com.android.tools#annotations;25.2.0 ...

[info] Resolving com.android.tools.build#builder-test-api;2.2.0 ...

[info] Resolving com.android.tools.ddms#ddmlib;25.2.0 ...

[info] Resolving com.android.tools#common;25.2.0 ...

[info] Resolving com.google.guava#guava;18.0 ...

[info] Resolving net.sf.kxml#kxml2;2.3.0 ...

[info] Resolving com.android.tools#sdklib;25.2.0 ...

[info] Resolving com.android.tools.layoutlib#layoutlib-api;25.2.0 ...

[info] Resolving com.intellij#annotations;12.0 ...

[info] Resolving com.android.tools#dvlib;25.2.0 ...

[info] Resolving com.android.tools#repository;25.2.0 ...

[info] Resolving org.apache.commons#commons-compress;1.8.1 ...

[info] Resolving com.google.jimfs#jimfs;1.1 ...

[info] Resolving com.google.code.gson#gson;2.2.4 ...

[info] Resolving org.apache.httpcomponents#httpclient;4.1.1 ...

[info] Resolving org.apache.httpcomponents#httpcore;4.1 ...

[info] Resolving commons-logging#commons-logging;1.1.1 ...

[info] Resolving commons-codec#commons-codec;1.4 ...

[info] Resolving org.apache.httpcomponents#httpmime;4.1 ...

[info] Resolving com.android.tools#sdk-common;25.2.0 ...

[info] Resolving org.bouncycastle#bcprov-jdk15on;1.48 ...

[info] Resolving com.android.tools.build#manifest-merger;25.2.0 ...

[info] Resolving com.android.tools.jack#jack-api;0.11.0 ...

[info] Resolving com.android.tools.jill#jill-api;0.10.0 ...

[info] Resolving com.android.tools.analytics-library#protos;25.2.0 ...

[info] Resolving com.google.protobuf#protobuf-java;2.5.0 ...

[info] Resolving com.android.tools.analytics-library#shared;25.2.0 ...

[info] Resolving com.android.tools.analytics-library#tracker;25.2.0 ...

[info] Resolving com.squareup#javawriter;2.5.0 ...

[info] Resolving org.ow2.asm#asm;5.0.4 ...

[info] Resolving org.ow2.asm#asm-tree;5.0.4 ...

[info] Resolving org.bouncycastle#bcpkix-jdk15on;1.51 ...

[info] Resolving org.bouncycastle#bcprov-jdk15on;1.51 ...

[info] Resolving com.android.tools.build#gradle-core;2.2.0 ...

[info] Resolving com.android.tools.lint#lint;25.2.0 ...

[info] Resolving com.android.tools.lint#lint-checks;25.2.0 ...

[info] Resolving com.android.tools.lint#lint-api;25.2.0 ...

[info] Resolving com.android.tools.external.lombok#lombok-ast;0.2.3 ...

[info] Resolving org.ow2.asm#asm-analysis;5.0.4 ...

[info] Resolving org.eclipse.jdt.core.compiler#ecj;4.5.1 ...

[info] Resolving com.android.tools.build#transform-api;2.0.0-deprecated-use-gradle-api ...

[info] Resolving com.android.tools.build#gradle-api;2.2.0 ...

[info] Resolving com.android.databinding#compilerCommon;2.2.0 ...

[info] Resolving com.android.databinding#baseLibrary;2.2.0 ...

[info] Resolving org.antlr#antlr4;4.5.3 ...

[info] Resolving commons-io#commons-io;2.4 ...

[info] Resolving com.googlecode.juniversalchardet#juniversalchardet;1.0.3 ...

[info] Resolving org.ow2.asm#asm-commons;5.0.4 ...

[info] Resolving org.jacoco#org.jacoco.core;0.7.5.201505241946 ...

[info] Resolving org.ow2.asm#asm-debug-all;5.0.1 ...

[info] Resolving org.jacoco#org.jacoco.report;0.7.5.201505241946 ...

[info] Resolving net.sf.jopt-simple#jopt-simple;4.9 ...

[info] Resolving org.antlr#antlr;3.5.2 ...

[info] Resolving org.antlr#antlr-runtime;3.5.2 ...

[info] Resolving org.antlr#ST4;4.0.8 ...

[info] Resolving com.android.tools.external.com-intellij#uast;145.597.4 ...

[info] Resolving net.orfjackal.retrolambda#retrolambda;2.3.0 ...

[info] Resolving com.timushev.sbt#sbt-updates;0.1.10 ...

[info] Resolving net.virtual-void#sbt-dependency-graph;0.8.2 ...

[info] Resolving com.github.mdr#ascii-graphs_2.10;0.0.3 ...

[info] Resolving org.scala-sbt#sbt;0.13.15 ...

[info] Resolving org.scala-sbt#main;0.13.15 ...

[info] Resolving org.scala-sbt#actions;0.13.15 ...

[info] Resolving org.scala-sbt#classpath;0.13.15 ...

[info] Resolving org.scala-lang#scala-compiler;2.10.6 ...

[info] Resolving org.scala-sbt#interface;0.13.15 ...

[info] Resolving org.scala-sbt#io;0.13.15 ...

[info] Resolving org.scala-sbt#control;0.13.15 ...

[info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...

[info] Resolving org.scala-sbt#completion;0.13.15 ...

[info] Resolving org.scala-sbt#collections;0.13.15 ...

[info] Resolving jline#jline;2.14.3 ...

[info] Resolving org.scala-sbt#api;0.13.15 ...

[info] Resolving org.scala-sbt#classfile;0.13.15 ...

[info] Resolving org.scala-sbt#logging;0.13.15 ...

[info] Resolving org.scala-sbt#process;0.13.15 ...

[info] Resolving org.scala-sbt#compiler-integration;0.13.15 ...

[info] Resolving org.scala-sbt#incremental-compiler;0.13.15 ...

[info] Resolving org.scala-sbt#relation;0.13.15 ...

[info] Resolving org.scala-sbt#compile;0.13.15 ...

[info] Resolving org.scala-sbt#persist;0.13.15 ...

[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...

[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.15 ...

[info] Resolving org.scala-sbt#ivy;0.13.15 ...

[info] Resolving org.scala-sbt#cross;0.13.15 ...

[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4 ...

[info] Resolving com.jcraft#jsch;0.1.50 ...

[info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...

[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...

[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...

[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...

[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...

[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...

[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...

[info] Resolving org.scala-sbt#run;0.13.15 ...

[info] Resolving org.scala-sbt#task-system;0.13.15 ...

[info] Resolving org.scala-sbt#tasks;0.13.15 ...

[info] Resolving org.scala-sbt#tracking;0.13.15 ...

[info] Resolving org.scala-sbt#cache;0.13.15 ...

[info] Resolving org.scala-sbt#testing;0.13.15 ...

[info] Resolving org.scala-sbt#test-agent;0.13.15 ...

[info] Resolving org.scala-sbt#test-interface;1.0 ...

[info] Resolving org.scala-sbt#main-settings;0.13.15 ...

[info] Resolving org.scala-sbt#apply-macro;0.13.15 ...

[info] Resolving org.scala-sbt#command;0.13.15 ...

[info] Resolving org.scala-sbt#template-resolver;0.1 ...

[info] Resolving org.scala-sbt#logic;0.13.15 ...

[info] Resolving org.scala-sbt#compiler-interface;0.13.15 ...

[info] Resolving org.scala-lang#jline;2.10.6 ...

[info] Resolving org.fusesource.jansi#jansi;1.4 ...

[info] Done updating.

**Comment by zyh001** [comment]
我看到android官网上提到过不再支持armeabi-v7a，[https://android.googlesource.com/platform/ndk/+/353e653824b79c43b948429870d0abeedebde386/docs/HardFloatAbi.md](https://android.googlesource.com/platform/ndk/+/353e653824b79c43b948429870d0abeedebde386/docs/HardFloatAbi.md)

**Comment by Akkariiin** [comment]
```
We're removing support for the armeabi-v7a-hard ABI. Anyone targeting this ABI should target armeabi-v7a instead.
```
跟这没关系


另外上面贴的这么长一段我没看到错误在哪里呀

**Comment by zyh001** [comment]
@Akkariiin 现在还是这个错误`[error] make: *** No rule to make targetjni/libancillary/fd_recv.c', needed by obj/local/armeabi-v7a/objs/ancillary/libancillary/fd_recv.o'. Stop.`
我估计是我NDK的问题，但是我降级到r12b和r11都不行，一样的错误:(

**Comment by zyh001** [comment]
@Akkariiin 您能不能把您那边各种库的版本发过来，我参考一下☺

**Comment by Akkariiin** [comment]
进入jni/下的各个目录看看版本是不是正确

有gui环境的话，建议使用smartgit来查看

我猜是代码不完整

见：https://github.com/shadowsocks/shadowsocks-android/issues/974  以及  https://github.com/lparam/xSocks-android/issues/5
