### ISSUE TITLE
小米平板2 MIUI9   8.3.15  运行' SSR3.4.0.5 或者SSRR 3.5.4  已连接 平板就马上关机

### ISSUE THREAD

**Issue by overkiss** [shadowsocksrr/shadowsocksr-android#101]
小米平板2 MIUI9   8.3.15  运行' SSR3.4.0.5 或者SSRR 3.5.4  已连接 平板就马上关机
 
SSR 使用两年多没有出现过这种情况
SSRR 之前也有用过 没有出现前面情况
 不知道什么原因会出现这种一点连接马上就关机  俺已经试过好多次是这样的

**Comment by MoonASS** [comment]
像这样的节点，ssrr ping延迟⚡️、连接时或连接后检查网络时会关机重启，很头疼而且如果设置开机自启，就得开机马上手动进软件，不然就是循环重启，手机华为emui4.0安卓6.0 已root ，3.5.4版，节点和加密协议如图，是用ssr截的图，面对这个节点怕怕的，因为订阅的节点不能总挨个看加密协议吧。ssr(3.4.0.6)面对这样的节点也有此类bug，ssr的是手动点击单个闪电⚡️按钮自动重启手机或批量闪电⚡️A按钮一定几率重启，点击飞机✈️和检查网络连接时则不会重启，之前我还以为是gfw攻击关机呢(●—●) 瑟瑟发抖。[ssr://MTU5LjY1Ljc4LjM0OjIyMTAyOm9yaWdpbjpub25lOnBsYWluOmJrcDJlU05WUUhvLz9vYmZzcGFyYW09JnByb3RvcGFyYW09JnJlbWFya3M9NWJpdTZLLVY1cTJrNklxQzU0SzU1NzZPNVp1OSZncm91cD01b2lSNUxpQTU1U281YkN4NVlXejVweTY]
![screenshot_2018-04-03-20-05-29](https://user-images.githubusercontent.com/38038950/38248593-7b465718-377b-11e8-87a3-9296543d2699.png)

**Comment by chr56** [comment]
+1 启动服务时马上黑屏关机重启

仅一个节点有这样情况，现在已更换节点，并重置，关闭TCP fast open。

xposed向来已有，有没有更新过模块，以前一直没事。

日志是重启后马上打开提取的。（log貌似没有记录吧？）

--------- beginning of main
05-01 12:59:00.925  8076  8076 I XLua.Xposed: Loaded in.zhaoj.shadowsocksrr:10103
05-01 12:59:00.933  8076  8076 W XPrivacy: Hooking package=in.zhaoj.shadowsocksrr
05-01 12:59:01.071  8076  8091 E linker  : readlink('/proc/self/fd/37') failed: Permission denied [fd=37]
05-01 12:59:01.071  8076  8091 E linker  : warning: unable to get realpath for the library "/system/lib/hw/gralloc.hi3630.so". Will use given name.
05-01 12:59:01.073  8076  8091 E linker  : readlink('/proc/self/fd/37') failed: Permission denied [fd=37]
05-01 12:59:01.073  8076  8091 E linker  : warning: unable to get realpath for the library "libion.so". Will use given name.
05-01 12:59:01.076  8076  8091 E HAL     : load: id=gralloc != hmi->id=gralloc
05-01 12:59:01.318  8076  8076 W ShadowsocksApplication: Unknown zh locale script: . Falling back to trying countries...
05-01 12:59:01.348  8076  8099 E linker  : readlink('/proc/self/fd/43') failed: Permission denied [fd=43]
05-01 12:59:01.349  8076  8099 E linker  : warning: unable to get realpath for the library "/system/framework/oat/arm/com.android.location.provider.odex". Will use given name.
05-01 12:59:01.353  8076  8099 E linker  : readlink('/proc/self/fd/43') failed: Permission denied [fd=43]
05-01 12:59:01.353  8076  8099 E linker  : warning: unable to get realpath for the library "/data/dalvik-cache/arm/system@framework@com.android.location.provider.jar@classes.dex". Will use given name.
05-01 12:59:01.357  8076  8099 E linker  : readlink('/proc/self/fd/43') failed: Permission denied [fd=43]
05-01 12:59:01.357  8076  8099 E linker  : warning: unable to get realpath for the library "/system/framework/oat/arm/com.android.media.remotedisplay.odex". Will use given name.
05-01 12:59:01.360  8076  8099 E linker  : readlink('/proc/self/fd/44') failed: Permission denied [fd=44]
05-01 12:59:01.360  8076  8099 E linker  : warning: unable to get realpath for the library "/data/dalvik-cache/arm/system@framework@com.android.media.remotedisplay.jar@classes.dex". Will use given name.
05-01 12:59:01.364  8076  8076 W GoogleTagManager: Failed to extract the container from the resource file. Resource is a UTF-8 encoded string but doesn't contain a JSON container
05-01 12:59:01.367  8076  8099 E linker  : readlink('/proc/self/fd/42') failed: Permission denied [fd=42]
05-01 12:59:01.367  8076  8099 E linker  : warning: unable to get realpath for the library "/data/app/com.google.android.gms-1/oat/arm/base.odex". Will use given name.
05-01 12:59:01.378  8076  8099 I XLua.Xposed: Loaded com.google.android.gms:10103
05-01 12:59:01.378  8076  8099 W XPrivacy: Hooking package=com.google.android.gms
05-01 12:59:01.926  8076  8076 E GoogleTagManager: Invalid macro: _gtm.loadEventEnabled
05-01 12:59:01.940  8076  8101 W GoogleTagManager: Failed to read the resource from disk. The resource is inconsistent
05-01 12:59:02.034  8076  8102 I System  : core_booster, getBoosterConfig = false
05-01 12:59:02.085  8076  8105 I System.out: [su]
05-01 12:59:02.085  8076  8105 I System.out: null
05-01 12:59:02.085  8076  8105 I System.out: null
05-01 12:59:02.087  8076  8105 I System.out: Calling by::className:de.robv.android.xposed.XposedBridge  MethodName:invokeOriginalMethodNative
05-01 12:59:02.124  8076  8102 I System  : core_booster, getBoosterConfig = false
05-01 12:59:02.165  8076  8076 I HwCust  : Constructor found for class android.app.HwCustHwWallpaperManagerImpl
05-01 12:59:02.194  8076  8076 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
05-01 12:59:02.535  8076  8105 I System.out: [su]
05-01 12:59:02.535  8076  8105 I System.out: null
05-01 12:59:02.535  8076  8105 I System.out: null
05-01 12:59:02.535  8076  8105 I System.out: Calling by::className:de.robv.android.xposed.XposedBridge  MethodName:invokeOriginalMethodNative
05-01 12:59:02.588  8076  8076 I JobManager: Found pending job request{id=285, tag=SSRSubUpdateJob}, canceling
05-01 12:59:02.641  8076  8076 I HwCust  : Constructor found for class android.app.HwCustAlarmManagerImpl
05-01 12:59:02.695  8076  8076 W InstanceID/Rpc: Found 10006
05-01 12:59:02.699  8076  8076 I SendBroadcastPermission: action:com.google.android.gms.gcm.ACTION_SCHEDULE, mPermissionType:0
05-01 12:59:02.875  8076  8102 E GoogleTagManager: Invalid macro: _gtm.loadEventEnabled
05-01 12:59:02.914  8143  8143 I XLua.Xposed: Loaded in.zhaoj.shadowsocksrr:10103
05-01 12:59:02.919  8143  8143 W XPrivacy: Hooking package=in.zhaoj.shadowsocksrr
05-01 12:59:03.014  8143  8163 E linker  : readlink('/proc/self/fd/37') failed: Permission denied [fd=37]
05-01 12:59:03.014  8143  8163 E linker  : warning: unable to get realpath for the library "/system/lib/hw/gralloc.hi3630.so". Will use given name.
05-01 12:59:03.015  8143  8163 E linker  : readlink('/proc/self/fd/37') failed: Permission denied [fd=37]
05-01 12:59:03.015  8143  8163 E linker  : warning: unable to get realpath for the library "libion.so". Will use given name.
05-01 12:59:03.017  8143  8163 E HAL     : load: id=gralloc != hmi->id=gralloc
05-01 12:59:03.023  8076  8141 E HAL     : load: id=gralloc != hmi->id=gralloc
05-01 12:59:03.024  8076  8141 I OpenGLRenderer: Initialized EGL, version 1.4
05-01 12:59:03.035  8076  8141 E linker  : readlink('/proc/self/fd/51') failed: Permission denied [fd=51]
05-01 12:59:03.035  8076  8141 E linker  : warning: unable to get realpath for the library "libhwaps.so". Will use given name.
05-01 12:59:03.049  8076  8141 E linker  : readlink('/proc/self/fd/56') failed: Permission denied [fd=56]
05-01 12:59:03.049  8076  8141 E linker  : warning: unable to get realpath for the library "/system/lib/libhwuibp.so". Will use given name.
05-01 12:59:03.267  8143  8143 W ShadowsocksApplication: Unknown zh locale script: . Falling back to trying countries...
05-01 12:59:03.289  8143  8191 E linker  : readlink('/proc/self/fd/44') failed: Permission denied [fd=44]
05-01 12:59:03.290  8143  8191 E linker  : warning: unable to get realpath for the library "/system/framework/oat/arm/com.android.location.provider.odex". Will use given name.
05-01 12:59:03.293  8143  8191 E linker  : readlink('/proc/self/fd/42') failed: Permission denied [fd=42]
05-01 12:59:03.293  8143  8191 E linker  : warning: unable to get realpath for the library "/data/dalvik-cache/arm/system@framework@com.android.location.provider.jar@classes.dex". Will use given name.
05-01 12:59:03.298  8143  8143 W GoogleTagManager: Failed to extract the container from the resource file. Resource is a UTF-8 encoded string but doesn't contain a JSON container
05-01 12:59:03.298  8143  8191 E linker  : readlink('/proc/self/fd/42') failed: Permission denied [fd=42]
05-01 12:59:03.298  8143  8191 E linker  : warning: unable to get realpath for the library "/system/framework/oat/arm/com.android.media.remotedisplay.odex". Will use given name.
05-01 12:59:03.300  8143  8191 E linker  : readlink('/proc/self/fd/42') failed: Permission denied [fd=42]
05-01 12:59:03.300  8143  8191 E linker  : warning: unable to get realpath for the library "/data/dalvik-cache/arm/system@framework@com.android.media.remotedisplay.jar@classes.dex". Will use given name.
05-01 12:59:03.306  8143  8191 E linker  : readlink('/proc/self/fd/42') failed: Permission denied [fd=42]
05-01 12:59:03.306  8143  8191 E linker  : warning: unable to get realpath for the library "/data/app/com.google.android.gms-1/oat/arm/base.odex". Will use given name.
05-01 12:59:03.319  8143  8191 I XLua.Xposed: Loaded com.google.android.gms:10103
05-01 12:59:03.319  8143  8191 W XPrivacy: Hooking package=com.google.android.gms
05-01 12:59:03.872  8143  8143 E GoogleTagManager: Invalid macro: _gtm.loadEventEnabled
05-01 12:59:04.040  8143  8195 E GoogleTagManager: Invalid macro: _gtm.loadEventEnabled
05-01 12:59:04.574  8076  8076 I 2DSDR   : APS: 2DSDR: AbsListView.edgeReached, we will clear SDR ratio
05-01 12:59:05.337  8076  8076 I 2DSDR   : APS: 2DSDR: AbsListView.FlingRunnable.endFling, we will clear SDR ratio
05-01 12:59:05.879  8076  8076 I GAv4    : Google Analytics 10.0.84 is starting up. To enable debug logging on a device run:
05-01 12:59:05.879  8076  8076 I GAv4    :   adb shell setprop log.tag.GAv4 DEBUG
05-01 12:59:05.879  8076  8076 I GAv4    :   adb logcat -s GAv4
05-01 12:59:05.919  8076  8201 W GAv4    : AnalyticsReceiver is not registered or is disabled. Register the receiver for reliable dispatching on non-Google Play devices. See http://goo.gl/8Rd3yj for instructions.
05-01 12:59:05.936  8076  8201 W GAv4    : CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions.
05-01 12:59:05.944  8076  8201 W GAv4    : AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.
05-01 12:59:06.054  8076  8202 I System.out: [sh]
05-01 12:59:06.054  8076  8202 I System.out: null
05-01 12:59:06.054  8076  8202 I System.out: null
05-01 12:59:06.055  8076  8202 I System.out: Calling by::className:de.robv.android.xposed.XposedBridge  MethodName:invokeOriginalMethodNative
05-01 12:59:06.229  8076  8076 I 2DSDR   : APS: 2DSDR: AbsListView.FlingRunnable.endFling, we will clear SDR ratio
05-01 12:59:06.522  8076  8202 E linker  : readlink('/proc/self/fd/77') failed: Permission denied [fd=77]
05-01 12:59:06.522  8076  8202 E linker  : warning: unable to get realpath for the library "/data/app/in.zhaoj.shadowsocksrr-1/lib/arm/libsystem.so". Will use given name.
05-01 12:59:06.531  8076  8202 I Shadowsocks: JNI_OnLoad
05-01 12:59:06.849  8076  8202 I System.out: [sh]
05-01 12:59:06.849  8076  8202 I System.out: null
05-01 12:59:06.849  8076  8202 I System.out: null
05-01 12:59:06.850  8076  8202 I System.out: Calling by::className:de.robv.android.xposed.XposedBridge  MethodName:invokeOriginalMethodNative
05-01 12:59:09.113  8076  8076 I 2DSDR   : APS: 2DSDR: AbsListView.FlingRunnable.endFling, we will clear SDR ratio
05-01 12:59:10.275  8076  8076 I System.out: [logcat, -d]
05-01 12:59:10.275  8076  8076 I System.out: null
05-01 12:59:10.275  8076  8076 I System.out: null
05-01 12:59:10.277  8076  8076 I System.out: Calling by::className:de.robv.android.xposed.XposedBridge  MethodName:invokeOriginalMethodNative

**Comment by Akkariiin** [comment]
``` 05-01 12:59:06.531 8076 8202 I Shadowsocks: JNI_OnLoad ```
然后挂掉？

怀疑是系统问题

**Comment by chr56** [comment]
差不多，反应就像软重启

**Comment by Akkariiin** [comment]
```
05-01 12:59:06.522 8076 8202 E linker : warning: unable to get realpath for the library "/data/app/in.zhaoj.shadowsocksrr-1/lib/arm/libsystem.so". Will use given name.
```

这看起来是个加载库失败
试试重新安装，要不然就和系统或者X框架里面的插件有关

**Comment by chr56** [comment]
已经没有出现过这种情况，谢谢。

**Comment by Akkariiin** [comment]
@chr56 那就是xposed抽风，我也有遇到过
之后会随着重启随机出现
