### ISSUE TITLE
問一下，現在，ssrr如何截圖？

### ISSUE THREAD

**Issue by Nine499** [shadowsocksrr/shadowsocksr-android#108]
rt

**Comment by Akkariiin** [comment]
不能截图，此举是防止系统生成后台程序预览的

**Comment by aorosora** [comment]
安全原因，你可以通过安装xposed进行截图录屏操作

**Comment by jizusun** [comment]
还是不太明白，“阻止屏幕截图”的目的是？

**Comment by Akkariiin** [comment]
@smilingsun 目的是防止你在地铁/公交上玩手机的时候切换应用被站在你后面的热情群众/热心警察看到你在用SSR这类软件从而请你喝杯茶。
这个是有先例的，站在地铁玩手机被热心警察拍到开了VPN然后喝茶写检讨。

**Comment by DoveAz** [comment]
> @SmilingSun 目的是防止你在地铁/公交上玩手机的时候切换应用被站在你后面的热情群众/热心警察看到你在用SSR这类软件从而请你喝杯茶。
> 这个是有先例的，站在地铁玩手机被热心警察拍到开了VPN然后喝茶写检讨。

...那热心群众也是拍照吧,这完全是只能防自己啊
