### ISSUE TITLE
ssrr除了全局无法启用gcm/fcm

### ISSUE THREAD

**Issue by lzl119** [shadowsocksrr/shadowsocksr-android#110]
目前shadosocks启动绕过大陆与局域网，不使用分应用代理功能激活fcm正常，ssrr无论是否启用分应用代理，在非全局模式下都无法启用gcm和fcm推送。设备：三星s9+，系统版本Android8.0.0

**Comment by lzl119** [comment]
使用gcm测试用的app进行测试，ssrr只能在未开启分应用代理并且全局下正确激活fcm和gcm，使用其他的代理模式，fcm服务器连接失败，原因暂未知晓，这里无法提供图片，如果可以能够提供截图

**Comment by Akkariiin** [comment]
分应用代理是否添加了所有谷歌相关服务及进程，GCM使用了多个不同名称的应用及服务来提供服务，所以需要将所有名字中包含```google```的应用及不包含```google```但仍属于```google```相关服务的应用都加入分应用代理的被代理应用列表

**Comment by lzl119** [comment]
目前是除了全局，其他的方式也不能激活，无论知否开启分应用，也不排除我前几天在海南，网络环境问题，我今天再测试一下

**Comment by Akkariiin** [comment]
@lzl119 请务必在网络情况良好的情况下进行测试，现已知在网络质量较差的情况下即使国内应用仍然可正常使用，SSR的协议簇也会出现无法正常工作的情况。

**Comment by lzl119** [comment]
好的
		
		

		获取 Outlook for iOS
	




On Thu, Mar 29, 2018 at 1:20 PM +0800, "Akkariiin" <notifications@github.com> wrote:












@lzl119 请务必在网络情况良好的情况下进行测试，现已知在网络质量较差的情况下即使国内应用仍然可正常使用，SSR的协议簇也会出现无法正常工作的情况。

**Comment by lzl119** [comment]
经过测试，同一个vps在用ss的时候，可以激活，而SSRR无法激活，目前不知道是否为三星通病，以下是GCM/FCM在play服务连接的检测

		
		

		获取 Outlook for iOS
	





On Thu, Mar 29, 2018 at 3:43 PM +0800, "zhenglin lv" <lzl1194479418@gmail.com> wrote:













	
		
		
	
		好的
		
		

		获取 Outlook for iOS
	




On Thu, Mar 29, 2018 at 1:20 PM +0800, "Akkariiin" <notifications@github.com> wrote:












@lzl119 请务必在网络情况良好的情况下进行测试，现已知在网络质量较差的情况下即使国内应用仍然可正常使用，SSR的协议簇也会出现无法正常工作的情况。

**Comment by jameswarter** [comment]
开启分应用代理并开启“略过模式”应该可以吧

**Comment by lzl119** [comment]
目前看来是三星的rom问题，部分vps无法开启fcm，但是在一加手机上却可以开启，断流也是三星的问题




获取 Outlook for Android







On Mon, Jun 11, 2018 at 8:54 AM +0800, "warter" <notifications@github.com> wrote:












开启分应用代理并开启“略过模式”应该可以吧
