### ISSUE TITLE
安卓8.1分应用代理无效

### ISSUE THREAD

**Issue by ForbAvalon** [shadowsocksrr/shadowsocksr-android#113]
若没有开启绕行模式，则无论应用是否选中都无法访问VPN。
若开启绕行模式，则无论是否选中都能够通过vpn。
何解？

**Comment by Akkariiin** [comment]
请提供使用的ROM型号

---

分应用代理直接调用安卓系统VPN框架提供的功能。
故，如无法使用且确认操作无误，可确认为ROM未实现此项功能。

**Comment by ForbAvalon** [comment]
Lineage 15.1 r15
Oneplus X
8.1.0

2018年3月28日 下午12:25，Akkariiin <notifications@github.com>写道：

请提供使用的ROM型号

________________________________

分应用代理直接调用安卓系统VPN框架提供的功能。
故，如无法使用且确认操作无误，可确认为ROM未实现此项功能。

**Comment by ForbAvalon** [comment]
应该是rom的问题吧，我用影梭也是一样的情况
