### ISSUE TITLE
请问不包含google但仍属于google相关服务的应用都有哪些？

### ISSUE THREAD

**Issue by a8778700** [shadowsocksrr/shadowsocksr-android#114]
我开了分应用代理勾上了带google的程序，但是谷歌账户登不了，play可以上且下载
youtube要登录帐号显示不能连接

**Comment by Asutorufa** [comment]
用bypass，把国内应用过滤了不就行了

**Comment by Akkariiin** [comment]
谷歌自家的谷歌文档，谷歌PEF，谷歌幻灯片，谷歌翻译，谷歌地球，谷歌地图，谷歌街景，谷歌表格，Play商店，Play图书，Play音乐，Play游戏，Play Services Info，Play Service，YT Music，youtube，Gmail，安卓原生版日历，谷歌身份验证器，安卓自带的下载

上面列出的都是我曾经用过的属于谷歌家但是应用名中一般不写```google```或者```谷歌```的应用或服务

其中需要特别注意的是```下载```这个应用虽然不直接属于谷歌，但是谷歌各个应用包括Play商店都会隐式地调用```下载```这个应用来下载文件，所以也请将```下载```这个应用加入到代理列表中去

**Comment by Sanly** [comment]
AutoLoginService
