### ISSUE TITLE
关于8.0断流的可能问题解决方式

### ISSUE THREAD

**Issue by lcpp1123** [shadowsocksrr/shadowsocksr-android#118]
私人梯子，一个人用。最近发现在公司时就断流，在家使用还OK。今天彻底IOS有效，安卓失效，最好IOS也失效了。
所以：重新部署一边VPS就好了！SSRR，防火墙等都更新到最新。
希望对各位有帮助。

**Comment by lcpp1123** [comment]
补充一下。顺便重置升级了路由器固件等。

**Comment by Comah** [comment]
发觉aes-128-md5会被电信干扰的很厉害  手机用电信4G 各种断流断线 切到去联通4G（一机双卡）马上秒通秒满速。。。不知道你用的是哪个协议？

**Comment by Amoxicillen** [comment]
和VPS根本没有关系。我是买的节点，有十几个。两个笔记本电脑、一台Android6Nexus5、还有Android8.0的美版GalaxyS8，唯独S8抽筋断流，其他设备全都正常。所以根本不是VPS服务器的问题。

**Comment by Akkariiin** [comment]
#90
