### ISSUE TITLE
安卓8.1无法使用

### ISSUE THREAD

**Issue by L0snight** [shadowsocksrr/shadowsocksr-android#119]
我的手机系统是Lineage 15.1的安卓8.1版本，手机是一加2。现在手机上同时装有shadowsocks和shadowsocksR，shadowsocks可以使用，但当打开shadowsocksR,，开启代理会出现，后台服务启动失败：无法连接远程服务器：Cannot  run program  "/data/user/0/in.zhaoj. ........'

**Comment by L0snight** [comment]
补充：通过logcat查看了完整报错：Shadowsocks: Error to start VPN service: 无法连接远程服务器: Cannot run program "/data/user/0/in.zhaoj.shadowsocksrr/tun2socks": error=13, Permission denied

**Comment by L0snight** [comment]
已经解决。看了报错原因，我猜是权限不够的问题，涉及到三个文件，pdnsd,tun2socks,ss-local，这三个文件均只有rw-------权限，没有执行权限，所以只需要将这三个文件的权限改为rwx------即可正常运行

**Comment by 66beta** [comment]
一加3T 8.0，同样的问题，谢谢！

**Comment by NookyPOP** [comment]
@nncy 你好，那三个文件在哪儿？

**Comment by NookyPOP** [comment]
@nncy 整好了，谢谢

**Comment by BuaaJeco** [comment]
very good, problem solved!

**Comment by hexnullway** [comment]
@NookyPOP,请问您是怎么解决的

**Comment by fairytale110** [comment]
> @nncy 你好，那三个文件在哪儿？

在 /data/user/0/in.zhaoj.shadowsocksrr/tun2socks
需要root权限 用RE管理器进去改，我是root后出血的这个问题，确实有效
