### ISSUE TITLE
三星 S9+  3.5.4的一个BUG

### ISSUE THREAD

**Issue by CatSamaDD** [shadowsocksrr/shadowsocksr-android#121]
不知道是不是8.0专有的
我有一条线路是阿里云日本线 ，然后我玩的一个手游是BAN了阿里云的，用阿里云IP是连不上的。

现在这BUG就是：
我用阿里云线路本身可以正常翻墙，google play什么的都可以上，但是我一旦用这条线路去玩那个手游，游戏里提示我网络连接错误，这个时候我再切成其他本来可以使用的线路，会发现线路连接上之后没有速度，测速提示 failed to connect to www.google.com
而且这个BUG一旦出现，其他任何代理工具也都用不了了，SS用不了，UU加速器也用不了。
重置后台关了重开甚至重装软件都不能解决，只有重启手机能解决。

这个BUG不是时不时发生，而是我可以100%复现的

我试了SSR的安卓端最后一个版本，也有这个问题。

希望能提供下解决方法

**Comment by CatSamaDD** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1712
好像跟这个问题非常相似
应该是三星手机的问题，看来软件层面上解决不了

**Comment by progmboy** [comment]
三星s9+
也有这问题，这个问题真是闹心的很

**Comment by edorphin** [comment]
我也是被此问题困扰 未找到什么原因

**Comment by Amoxicillen** [comment]
我也是我也是！美版Galaxy S8 上上周刚升级到8.0就发现有不定期断流，但是我的一加手机在8.0和安卓7都没用断流的问题！

**Comment by lan5635** [comment]
给个信息，三星 Android8.0用户 在安装完ssr后，一定要到最近任务界面锁定ssr任务，然后在智能管理器那里打开ssr的自启动，这样ssr就不会被三星系统自动杀掉了
断流的问题应该是8.0的问题，等更新吧
看了下issue列表，全是三星orAndroid8.0  谷歌全锅

**Comment by Amoxicillen** [comment]
我目前只看到1位于一加5的用户，其他人都是三星。。。  这次买S8碰到ssr断流的体验真的是让我好不舒服。。  可惜太穷买不起pixel2

**Comment by sportfit** [comment]
I use one plus 3T without this phenomenon at android 8.0.

**Comment by Akkariiin** [comment]
#90

**Comment by vainglory403** [comment]
现在仍然不能用吧 @Akkariiin

**Comment by Akkariiin** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1712#issuecomment-377471063

**Comment by leowood2000** [comment]
same issues with my new galaxy Note 9 , 太吓人了，已经全部加了自启动，避免电池优化等等，

**Comment by ghost** [comment]
截止到目前依然有问题
