### ISSUE TITLE
Can not delete subscriptions on Amazon fire tv stick

### ISSUE THREAD

**Issue by yaozhang-this** [shadowsocksrr/shadowsocksr-android#124]
Problem: The default delete actions on android, which is swipe to delete, can not work on amazon tv sticks and this let the ssr only access the default freessrpublic and prevents it from accessing any later added subscriptions.

**Comment by Akkariiin** [comment]
sorry for that, i cannot test this and to find why.


alternative plan:
subject the subscriptions on your phone or PC to get the server config, 
then input to your tv sticks to let it work.

or make a soft router and run ssr on it.

**Comment by Akkariiin** [comment]
i think it may case by a Non-touch-able devices.

**Comment by husam-r** [comment]
I'm having the same problem. devices like the fire stick or android tv boxes don't have gesture support, so we can't swipe to remove "FreeSSR-public"

**Comment by kenkwan86** [comment]
also having the same issue. 
I cant swipe on the TV, even though i am already using a mouse and/or keyboard.

Most TV also wouldnt have NFC or camera to scan a QR Code. So i dont know how to manually share the server config.
