### ISSUE TITLE
auth_chain是否会增加内存消耗

### ISSUE THREAD

**Issue by iMusi** [shadowsocksrr/shadowsocksr-android#125]
看了之前小姐姐给其它人的回复自用chacha20+auth_chain所以我就用了chacha20+auth_chain_b+plain.
结果发现内存占用大了很多，**特别是开了多个端口以后**。
    这是因为auth_chain系列的原因吗。能否推荐个搭配，我这主要玩游戏+多端口。
多端口
![1](https://user-images.githubusercontent.com/27476494/38686069-0af13de8-3ea6-11e8-94b6-8d631c11434d.png)
单端口
![2](https://user-images.githubusercontent.com/27476494/38686044-fa0ff186-3ea5-11e8-88ae-123d9ef21a53.png)

**Comment by iMusi** [comment]
none+auth_chain+plain这样可以吗

**Comment by Akkariiin** [comment]
占用500+这很不正常，除非有很多用户使用或者用户中有使用BT的存在。
或者服务器端没有更新到最新版的SSRR，在去年年底/今年年初的几个提交中修复了多个内存泄漏问题。

<hr/>

使用none+auth_chain+plain是没有太大问题的
