### ISSUE TITLE
无法使用部分协议

### ISSUE THREAD

**Issue by SakuraChanNya** [shadowsocksrr/shadowsocksr-android#131]
我用小米手机，无法连接最新的auth_chain_e和f。只能用d和以前的协议，这是什么问题？
电脑版可以用auth_chain_e和f，就是手机版不行
显示Handshake failed和connection closed by peer。
请问怎么解决？

**Comment by Akkariiin** [comment]
安卓的e/f暂时还有问题未解决，请使用b或者d
