### ISSUE TITLE
关于GCM推送120秒断开重连的问题

### ISSUE THREAD

**Issue by crazystone19840328** [shadowsocksrr/shadowsocksr-android#134]
ss,ssr,ssrr绕行国产应用，GCM推送每120s就会断开，然后重连，不会发送心跳，服务器timeout是300，今天试了一下v2ray，用同样的一个节点，心跳正常了，大家可以探讨下，实在不喜欢用v2ray，还是ss系列用着舒服

**Comment by poemsiu** [comment]
试试 push notification fixer？
