### ISSUE TITLE
发现一个新问题，SSRR连接后过一段时间Twitter，Facebook等都可以正常刷时间线，唯独Instagram会断流

### ISSUE THREAD

**Issue by seoho8908** [shadowsocksrr/shadowsocksr-android#135]
发现一个新问题，SSRR连接后过一段时间Twitter，Facebook等都可以正常刷时间线，唯独Instagram、YouTube会断流，不知道大家有没有遇到过。

**Comment by sportfit** [comment]
No matter whether it is frequently switching links or always linking, the normal use of this phenomenon does not occur. I do not know which area of the server you are using. You may encounter this phenomenon when you encounter a link with a US server recently.

**Comment by poemsiu** [comment]
你是什么手机？

**Comment by seoho8908** [comment]
@mrzenwell
 Samsung Galaxy S8+

**Comment by Akkariiin** [comment]
#90
