### ISSUE TITLE
关于三星S9/8系列8.0更新后vpn断流问题向开发者提出的建议

### ISSUE THREAD

**Issue by poemsiu** [shadowsocksrr/shadowsocksr-android#137]
国外广告屏蔽app adguard在该机型使用时遇到了同样的问题，该app开发者在https://github.com/AdguardTeam/AdguardForAndroid/issues/1770  提出了app内的临时解决方案，ssrr开发者能否借鉴？

**Comment by Akkariiin** [comment]
#90
