### ISSUE TITLE
安卓8.0移动网络状态下无法登录Google系app

### ISSUE THREAD

**Issue by ShermanQ** [shadowsocksrr/shadowsocksr-android#138]
如题，手机型号:小米6MIUI9 安卓8.0，在移动网络下链接ssr无法登录除Play商店的其他Google系app，均显示无法连接至服务器。经抓包测试，其app会发送请求至google.cn的服务器地址。所有网页应用一切正常。
  WiFi网络下一切正常。

**Comment by Comah** [comment]
我的是原生8.1 装了全家桶   之前这个问题就反映过 不过我的手机连接到3.99ssr 除了谷歌地图位置、谷歌语音连接不上 其他都一切正常 谷歌位置、谷歌语音的地址估计没有强制转发 用的是白名单

**Comment by Comah** [comment]
我的安卓原生8.1全家桶一切正常

**Comment by rhjdvsgsgks** [comment]
Android 8.1的锅，打开nat模式就好了
