### ISSUE TITLE
关于此代码的build坑 我还在坑里

### ISSUE THREAD

**Issue by DreamSeekerKaiser** [shadowsocksrr/shadowsocksr-android#143]
自学安卓开发俩小时了 搞这个东西遇到了如下问题
1 直接git clone 此代码 在 安装git 子模块的时候会有问题 无法安装 或者 clone子模块的时候需要登陆github 需要该模块下的权限  切换分支也无法解决 依然存在同样问题 注释掉子模块引用还是无法解决 我最后发现 直接 clone 指定分支 阿卡丽小姐姐的develop 是可以的 
2 用安卓studio 打开项目无法识别 不能点击build按钮 我之前随便新建项目都是直接可以Build的 直接选虚拟机安装就可以了 这个 没有 看来安卓studio是个垃圾IDE 不建议大家使用 

3 sbt  该命令 不存在ubuntu16.04下  安装了这个命令之后 执行 sbt native-build clean android:package-release 
大面积报错  错误日志如下 
sbt native-build clean android:package-release
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading project definition from /home/kaiser/shadowsocksr-android/project
[info] Set current project to shadowsocksr (in build file:/home/kaiser/shadowsocksr-android/)
[info] ~/shadowsocksr-android/src/main ~/shadowsocksr-android
[info] Android NDK: WARNING: APP_STL stlport_static is deprecated and will be removed in the next release. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    
[info] Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module sodium    
[info] Android NDK:   shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2-impl.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-load-sse2.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-load-sse41.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-round.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/onetimeauth_poly1305.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna32.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna64.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/crypto_scrypt.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/pbkdf2-sha256.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/sysendian.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/scalarmult_curve25519.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/base.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/base2.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/d.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/d2.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/fe.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_add.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_madd.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_msub.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_p2_dbl.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_sub.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/pow22523.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/pow225521.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/sc.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/sqrtm1.h shadowsocks-libev/libsodium/src/libsodium/crypto_stream/chacha20/stream_chacha20.h shadowsocks-libev/libsodium/src/libsodium/crypto_stream/chacha20/ref/stream_chacha20_ref.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/curve25519_ref10.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/fe.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/montgomery.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/pow225521.h    
[info] Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module sodium    
[info] Android NDK:   shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2-impl.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-load-sse2.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-load-sse41.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-round.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/onetimeauth_poly1305.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna32.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna64.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/crypto_scrypt.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/pbkdf2-sha256.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/sysendian.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/scalarmult_curve25519.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/base.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/base2.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/d.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/d2.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/fe.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_add.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_madd.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_msub.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_p2_dbl.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_sub.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/pow22523.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/pow225521.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/sc.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/sqrtm1.h shadowsocks-libev/libsodium/src/libsodium/crypto_stream/chacha20/stream_chacha20.h shadowsocks-libev/libsodium/src/libsodium/crypto_stream/chacha20/ref/stream_chacha20_ref.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/curve25519_ref10.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/fe.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/montgomery.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/pow225521.h    
[info] [armeabi-v7a] Compile thumb  : proxychains4 <= libproxychains.c
[info] [armeabi-v7a] Compile thumb  : redsocks <= base.c
[info] [armeabi-v7a] Compile thumb  : redsocks <= http-connect.c
[info] [armeabi-v7a] Compile thumb  : redsocks <= log.c
[info] [armeabi-v7a] Compile thumb  : redsocks <= base64.c
[info] [armeabi-v7a] Compile thumb  : redsocks <= socks5.c
[info] [armeabi-v7a] Compile thumb  : redsocks <= http-relay.c
[info] [armeabi-v7a] Compile thumb  : redsocks <= main.c
[error] In file included from jni/redsocks/log.cIn file included from :22In file included from jni/redsocks/main.c:24:
[error] In file included from jni/libevent/event.h:44:
[error] jni/libevent/include/event2/event-config.h:450:13: error: typedef redefinition with different types ('int' vs 'unsigned long')
[error] typedef int fd_mask;
[error]             ^
[error] /home/kaiser/Android/Sdk/ndk-bundle/sysroot/usr/include/sys/select.h:40:23: note: previous definition is here
[error] typedef unsigned long fd_mask;
[error]                       ^
[error] :
[error] In file included from jni/libevent/event.h:44:
[error] jni/libevent/include/event2/event-config.h:450:13: error: typedef redefinition with different types ('int' vs 'unsigned long')
[error] typedef int fd_mask;
[error]             ^
[error] /home/kaiser/Android/Sdk/ndk-bundle/sysroot/usr/include/sys/select.h:40:23: note: previous definition is here
[error] typedef unsigned long fd_mask;
[error]                       ^
[error] In file included from jni/redsocks/http-relay.c:31:
[error] In file included from jni/redsocks/redsocks.h:6:
[error] In file included from jni/libevent/event.h:44:
[error] jni/libevent/include/event2/event-config.h:450:13: error: typedef redefinition with different types ('int' vs 'unsigned long')
[error] typedef int fd_mask;
[error]             ^
[error] /home/kaiser/Android/Sdk/ndk-bundle/sysroot/usr/include/sys/select.h:40:23: note: previous definition is here
[error] typedef unsigned long fd_mask;
[error]                       ^
[error] 1 error generated.
[error] jni/redsocks/base64.c:28:
[error] In file included from jni/redsocks/utils.h:6:
[error] In file included from jni/libevent/event.h:44:
[error] jni/libevent/include/event2/event-config.h:450:13: error: typedef redefinition with different types ('int' vs 'unsigned long')
[error] typedef int fd_mask;
[error]             ^
[error] /home/kaiser/Android/Sdk/ndk-bundle/sysroot/usr/include/sys/select.h:40:23: note: previous definition is here
[error] typedef unsigned long fd_mask;
[error]                       ^
[error] make: *** [obj/local/armeabi-v7a/objs/redsocks/redsocks/http-relay.o] Error 1
[error] make: *** Waiting for unfinished jobs....
[error] In file included from jni/redsocks/http-connect.c:31:
[error] In file included from jni/redsocks/redsocks.h:6:
[error] In file included from jni/libevent/event.h:44:
[error] jni/libevent/include/event2/event-config.h:450:13: error: typedef redefinition with different types ('int' vs 'unsigned long')
[error] typedef int fd_mask;
[error]             ^
[error] /home/kaiser/Android/Sdk/ndk-bundle/sysroot/usr/include/sys/select.h:40:23: note: previous definition is here
[error] typedef unsigned long fd_mask;
[error]                       ^
[error] In file included from jni/redsocks/socks5.c:21:
[error] In file included from jni/redsocks/utils.h:6:
[error] In file included from jni/libevent/event.h:44:
[error] jni/libevent/include/event2/event-config.h:450:13: error: typedef redefinition with different types ('int' vs 'unsigned long')
[error] typedef int fd_mask;
[error]             ^
[error] /home/kaiser/Android/Sdk/ndk-bundle/sysroot/usr/include/sys/select.h:40:23: note: previous definition is here
[error] typedef unsigned long fd_mask;
[error]                       ^
[error] jni/proxychains/src/libproxychains.c:483:17: error: conflicting types for 'gethostbyaddr'
[error] struct hostent *gethostbyaddr(const char *addr, int len, int type) {
[error]                 ^
[error] /home/kaiser/Android/Sdk/ndk-bundle/sysroot/usr/include/netdb.h:211:17: note: previous declaration is here
[error] struct hostent* gethostbyaddr(const void* __addr, socklen_t __length, int __type);
[error]                 ^
[error] 1 error generated.
[error] 1 error generated.
[error] make: *** [obj/local/armeabi-v7a/objs/redsocks/redsocks/main.o] Error 1
[error] 1 error generated.
[error] make: *** [obj/local/armeabi-v7a/objs/proxychains4/proxychains/src/libproxychains.o] Error 1
[error] 1 error generated.
[error] make: *** [obj/local/armeabi-v7a/objs/redsocks/redsocks/http-connect.o] Error 1
[error] make: *** [obj/local/armeabi-v7a/objs/redsocks/redsocks/log.o] Error 1
[error] 1 error generated.
[error] make: *** [obj/local/armeabi-v7a/objs/redsocks/redsocks/socks5.o] Error 1
[error] 1 error generated.
[error] make: *** [obj/local/armeabi-v7a/objs/redsocks/redsocks/base64.o] Error 1
[error] In file included from jni/redsocks/base.c:42:
[error] In file included from jni/redsocks/redsocks.h:6:
[error] In file included from jni/libevent/event.h:44:
[error] jni/libevent/include/event2/event-config.h:450:13: error: typedef redefinition with different types ('int' vs 'unsigned long')
[error] typedef int fd_mask;
[error]             ^
[error] /home/kaiser/Android/Sdk/ndk-bundle/sysroot/usr/include/sys/select.h:40:23: note: previous definition is here
[error] typedef unsigned long fd_mask;
[error]                       ^
[error] 1 error generated.
[error] make: *** [obj/local/armeabi-v7a/objs/redsocks/redsocks/base.o] Error 1
[error] Total time: 1 s, completed 2018-5-25 18:10:58
总结 ~~ 我就想弄个软件 翻个墙 怎么就这么难呢 这个人类社会的计算机设计这么这么不人性化 卧槽 想哭

**Comment by oxoxoxox** [comment]
https://github.com/shadowsocksrr/shadowsocksr-android/blob/Akkariiin/develop/README.md

这个里面的 PREREQUISITES 部分你看了么？我在 Ubuntu 16.04 和 Mac OS 上都能正常编译通过
