### ISSUE TITLE
功能支持

### ISSUE THREAD

**Issue by timwa0669** [shadowsocksrr/shadowsocksr-android#15]
android版不支持使用本地自定义acl文件，只支持使用网络acl文件。

**Comment by Akkariiin** [comment]
aes-gcm那个
ADAE模式会变更SS协议，所以本分支现在还没有支持ADAE的打算

从某种意义上来说上来说，ADAE带来的是Anti-CCA，而混淆插件或协议插件同样带来了Anti-CCA的能力，所以开了混淆插件或协议插件的SSR不需要ADAE。

**Comment by Akkariiin** [comment]
本地ACL功能需要安卓Scala开发者，安卓的开发我暂时抽不出时间来，所以这个功能会推后。
