### ISSUE TITLE
发现SSRWindows版不兼容Windows 10系统，能否升级下？

### ISSUE THREAD

**Issue by seoho8908** [shadowsocksrr/shadowsocksr-android#150]
发现SSRWindows版不兼容Windows 10系统，能否升级下？
@Akkariiin

**Comment by xin-ma-code** [comment]
我用得挺好，你可以说一下不兼容的具体表现看看

**Comment by 4512369781** [comment]
这里是安卓版的，你发错地方了。
另外问下系统是win10 17682么？我之前升级后就不能使用，直接提示无法访问代理服务器。进程里也出现很多个“pacjsworker.exe”，在上个预览版本也就是17677是正常的，也没有“pacjsworker.exe”这个文件的。
6.20：刚刚发现，17682以后，如果ie开了增强保护模式，就会无法访问代理，关了增强保护模式就正常了。
