### ISSUE TITLE
小米8 miui9.5 稳定版切换节点会导致所有节点无法连接

### ISSUE THREAD

**Issue by brendan0524** [shadowsocksrr/shadowsocksr-android#151]
连接某一个节点后 切换节点会导致所有节点无法连接。而且ssr连接过程中 会出现忽快忽慢的情况  望尽快修复

**Comment by lczzf** [comment]
Android 8.1一直都这样，无解

**Comment by Akkariiin** [comment]
https://github.com/shadowsocksrr/shadowsocksr-android/issues/90#issuecomment-412488010

切换之前断开连接，切完再连接
