### ISSUE TITLE
bug, 设置“分应用代理”后，无法测试互联网连接

### ISSUE THREAD

**Issue by Justsoos** [shadowsocksrr/shadowsocksr-android#161]
v3.5.1
估计是模块逻辑冲突了，设置分应用代理后（比如只代理google play），再去点标题的粉红色测试连接，将出现 “无互联网连接”，但实际上代理正常可用。

**Comment by LNDDYL** [comment]
@Akkariiin

**Comment by hamjin** [comment]
那是你没有让ssr自己走分应用代理，当然不行，这是android的分应用代理表现

**Comment by Akkariiin** [comment]
分应用代理要手动包括SSR自身
