### ISSUE TITLE
UDP转发无法绕过中国大陆IP

### ISSUE THREAD

**Issue by sqwwqw5** [shadowsocksrr/shadowsocksr-android#165]
版本：v3.5.4-alpha
机型：华为P20
系统：安卓8.1

当UDP转发开启时，即使路由选择绕过局域网和中国大陆，大陆IP走UDP的依然会走代理，表现为国内手游高PING。并且因为国内DNS是代理查询的，导致大陆版权视频无法观看。

TCP可以正常绕过。

我自己路由部署的OPENWRT则可以正常绕过大陆IP的UDP协议。

**Comment by joshua-kfbb** [comment]
目前可以用分应用代理来绕过问题

**Comment by Akkariiin** [comment]
请问华为P20有断流问题吗？
