### ISSUE TITLE
3.5.1.1小bug，检查网络连接失败

### ISSUE THREAD

**Issue by Portan** [shadowsocksrr/shadowsocksr-android#17]
每次检查网络连接时都会提示connection time out。但实际上是连接成功的而且程序使用正常。

以前检查网络连接时都会显示延迟时间。

**Comment by qhfls** [comment]
并未有次情况，是每次还是偶尔？

**Comment by Portan** [comment]
每次都是这样，我装了破娃最后的版本也是显示这样，是手机哪里设置的原因吗？

10-13 14:30:37.740 28271 28271 W IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
10-13 14:30:37.740 28271 28271 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
10-13 14:34:27.061 28271 28301 W OpenGLRenderer: cuilf pushLayerUpdate 309 delete mLayer: 0xcf9a2900, RenderLayer: 0xd00a9700
10-13 14:34:27.176 28271 28297 E GoogleTagManager: Invalid macro: _gtm.loadEventEnabled
10-13 14:34:29.379 28271 28271 W IInputConnectionWrapper: finishComposingText on inactive InputConnection

上面这些信息不知道有没有反应出connection time out的错误在哪里？

**Comment by Portan** [comment]
Sorry, 我把SSRR程序本身给设成绕行了。。打扰大家了。。
@qhfls 谢谢！
