### ISSUE TITLE
不支持舊版本安桌?

### ISSUE THREAD

**Issue by snowrice** [shadowsocksrr/shadowsocksr-android#171]
我的手機是android 4.0.4版本,安裝不了,請問什麼版本的SSR能安裝在安桌4.0.4手機上面?

**Comment by hamjin** [comment]
Must use in Android 4.4+
I prefer to use it in Android 5+

**Comment by Akkariiin** [comment]
https://github.com/shadowsocksrr/shadowsocksr-android/blob/7b02a6b9d3b1f61574d625bdf8250c267c85febe/src/main/AndroidManifest.xml#L25

最小sdk版本16
对应android 4.1

https://developer.android.com/about/versions/android-4.1
