### ISSUE TITLE
经测试，SS和rixcloudSSR安卓版在三星note8 8.1系统很稳定，无断流

### ISSUE THREAD

**Issue by xuexiaokang** [shadowsocksrr/shadowsocksr-android#172]
SS早在半年前已经解决断流问题，rixcloud应该也是找高人修改的，所以都没有断流问题。SSRR最新3.5.4依旧断流，而且对比发现，同一台香港节点，在SS和rixcloudSSR上网络测试延迟都只有很正常的一两百，但是在SSRR上连接后延迟却达到四千多，好像SSRR内部形成了回路或者通过哪里中转了一样，就算能连上，那测试结果也是很惨的，所以动不动就超时或者断流，毕竟延迟都高得离谱。测试机型：三星NOTE8国行8.0.0

**Comment by Akkariiin** [comment]
https://github.com/shadowsocksrr/shadowsocksr-android/issues/90#issuecomment-412488010
