### ISSUE TITLE
开启UDP转发后似乎所有流量都通过UDP传输了。

### ISSUE THREAD

**Issue by quanljh** [shadowsocksrr/shadowsocksr-android#176]
如题，我的服务端装了BBR加速，安卓客户端如果不开启UDP转发，Youtube看视频的速度维持在5M/S上下，但是开启UDP转发后，速度只有不到1M，相当于流量没有走TCP，而走的是UDP。我觉得应该是语音，视频，以及游戏这些走UDP，而不是全局啊，这样看来转发UDP流量就相当于全局转发了，有什么解决办法吗？

**Comment by Akkariiin** [comment]
不是很清楚是怎么回事，但是如果非必需的话你可以试着不打开UDP转发，某些服务器好像使用UDP转发会出问题
