### ISSUE TITLE
mi8无法使用导入二维码功能

### ISSUE THREAD

**Issue by snowKnight3** [shadowsocksrr/shadowsocksr-android#178]
点击导入二维码，提示没有可以使用的应用程序

**Comment by fuzitao** [comment]
你的小米8 手动配置后可以用吗？ 为什么我的用一会 就不行了，必须的重启才能正常，另一个android 7.0 正常使用。

**Comment by snowKnight3** [comment]
我在用旧版的ssr，除了不支持auth_chain_a与二维码从相册选取功能以外，其他功能很好用非常稳定

**Comment by immax1** [comment]
能说下那个版本吗？，米8这个版本经常断

**Comment by snowKnight3** [comment]
最新alpha版本，和上一个稳定版一样都不能用。就连相机都无法调用
