### ISSUE TITLE
扫描二维码bug？

### ISSUE THREAD

**Issue by snowKnight3** [shadowsocksrr/shadowsocksr-android#182]
点选了扫描二维码，被提示没有应用程序可执行这个功能

**Comment by 417788939** [comment]
你手机里面没有相机。。。

**Comment by snowKnight3** [comment]
xiaomi8了解一下，双摄像头。还有一部锤子科技的坚果pro也是双摄像头。
你跟我说没相机？

**Comment by 417788939** [comment]
没权限调用摄像头也可以认为找不到好吗。就算你有100个摄像头都一样。

我用的ssr就是没有摄像头权限的，一样提示没有相机。

**Comment by snowKnight3** [comment]
怎么才能有权限？我想使用摄像头

**Comment by linfeng001** [comment]
我的打开二维码就扫描不能在相册选择图片也没用啊

**Comment by Kennnnnnji** [comment]
在play store里面下载一个Barcode Scanner即可

**Comment by Akkariiin** [comment]
使用新版，新版自带一个内嵌的zxing二维码扫描组件会在系统中没有支持的扫描器时使用
或者从这里下载一个 https://github.com/zxing/zxing/releases
