### ISSUE TITLE
关于三星安卓8.x断流，实测可以通过转换成系统程序解决。

### ISSUE THREAD

**Issue by 417788939** [shadowsocksrr/shadowsocksr-android#183]
本人三星n8，安卓8.0系统，之前正常安装的情况下也是有断流情况，用着用着他就连不上网了，怎么测试都超时，不是节点问题。添加到电池优化白名单也不行。

后来我用Link2SD把它转换成系统应用以后，发现没有断流情况了。我已经用了一个月了没有发现断流问题。

**Comment by snowKnight3** [comment]
不懂啊，请问操作步骤是什么？另外，怎么才能调用摄像头？

**Comment by 417788939** [comment]
> 不懂啊，请问操作步骤是什么？另外，怎么才能调用摄像头？

你看看是否拒绝过摄像头申请权限，你去应用设置看看。

**Comment by snowKnight3** [comment]
完全没有这个权限选项

**Comment by fishmacs** [comment]
转换成系统应用需要root吧

**Comment by wangpeng119110** [comment]
> 本人三星n8，安卓8.0系统，之前正常安装的情况下也是有断流情况，用着用着他就连不上网了，怎么测试都超时，不是节点问题。添加到电池优化白名单也不行。
> 
> 后来我用Link2SD把它转换成系统应用以后，发现没有断流情况了。我已经用了一个月了没有发现断流问题。
这个是不是需要 ROOT 后才能操作？

**Comment by Akkariiin** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1712#issuecomment-377471063
