### ISSUE TITLE
安卓版订阅问题

### ISSUE THREAD

**Issue by shenmu33** [shadowsocksrr/shadowsocksr-android#185]
自己局域网架设了web服务，自己制作rss源，用局域网的地址，windows版本可以读的出来，但是安卓版读不粗来。
安卓电视真心不方便输入，希望可以修复这个bug。电视用扫描二维码和读取剪贴板都不好使，只有订阅是最方便的。

**Comment by Afanofgithub** [comment]
啥都不懂的小白注册了账号来问问，现在安卓版的ssrr最新版本是多少？windows10的呢？大家除了自己搭建还用的哪里的？我买的uefcloud，求推荐。现在无论手机端和电脑端都无法导入节点和订阅地址，求解答，感谢各位！！！

**Comment by Akkariiin** [comment]
请参照 https://github.com/shadowsocksrr/shadowsocks-rss/wiki/Subscribe-%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%A2%E9%98%85%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3

**Comment by shenmu33** [comment]
我都说了pc版测试可以，安卓版的不行，说明不是我写的有问题
算了，反正也不装电视上了
