### ISSUE TITLE
分应用代理无法快速应用到所有配置文件的问题

### ISSUE THREAD

**Issue by LidoCKT** [shadowsocksrr/shadowsocksr-android#189]
我的设置是依赖分应用代理的绕行模式，在一个配置文件下选好应用并勾选绕行，然后选择应用到所有配置文件，发现别的配置文件下没有开启分应用代理，有的配置文件开了分应用代理但没有勾选绕行模式，有的没开启分应用并在手动开启后还要手动开启分应用代理。
丧失了【应用到所有配置文件】本应有的便捷性，在很多配置文件的情况下还是很不便。

**Comment by Afanofgithub** [comment]
借个楼问下，连上了服务器，接受发送都有数据，但ins google play都和没开ssr一样，什么原因啊？谢谢各位聚聚

**Comment by Akkariiin** [comment]
@lidoworld 
什么设备？
再试一次。

@Afanofgithub 
选全局模式关掉分应用代理，或者分应用代理里面加上所有相关的应用
