### ISSUE TITLE
SSR&SSRR疑似遭遇系统级封锁

### ISSUE THREAD

**Issue by FishMagic** [shadowsocksrr/shadowsocksr-android#19]
MIUI在更新 *7.10.17* 后，SSR&SSRR中所有节点均无法连接，于其他设备或低版本正常使用
![screenshot_2017-10-17-21-26-19-837_in zhaoj shadowsocksr](https://user-images.githubusercontent.com/31554762/31672210-814d3aa8-b38e-11e7-82ae-d366d5274caf.png)

**Comment by Sak94664** [comment]
重装应用一次试一试，或者换第三方的系统(lineage etc.)

**Comment by Sak94664** [comment]
或者换成国际开发版也可以

**Comment by laincat** [comment]
问个题外这是啥字体？

**Comment by Sooele** [comment]
定制UI叫安卓！！！原生态儿子90％以上才叫Android

**Comment by Sak94664** [comment]
转至issue22

**Comment by Akkariiin** [comment]
#22
