### ISSUE TITLE
内置默认订阅会导致无线菊花转

### ISSUE THREAD

**Issue by ntgeralt** [shadowsocksrr/shadowsocksr-android#199]
你好，发现个小问题。

新的app装好后，添加了新订阅地址。如果不移除自带的默认订阅，会一直卡在‘’请稍后‘’，无法更新订阅，即使新订阅地址是可用的情况下，也会被自带的失效订阅地址卡住无法更新。

**Comment by Akkariiin** [comment]
因为内置默认订阅早就失效了
