### ISSUE TITLE
连接之后只能连得上QQ，无法访问其它网络

### ISSUE THREAD

**Issue by Chinakjc** [shadowsocksrr/shadowsocksr-android#205]
您好，我的设备是xperia xz premium，系统9.0，在移动网络下（目前还没有测试过WiFi），客户端突然出现连接以后无法访问网络但是可以连接QQ的问题，之前都没有出现过这个问题的，在电脑上也没有这个问题，重启系统，重装软件都无法解决，请问要如何解决这个问题？

**Comment by biaji** [comment]
DNS问题吧

**Comment by Chinakjc** [comment]
@biaji 请问这个问题要如何解决

**Comment by Akkariiin** [comment]
修改DNS设置
