### ISSUE TITLE
MIUI开发板升级后，开启SSRR提示错误: get package uid: Neither user 10208 nor current process has android permission

### ISSUE THREAD

**Issue by YueYueYue** [shadowsocksrr/shadowsocksr-android#22]
自用Mi6在今天的开发板升级后，开启SSRR提示错误：
 get package uid: Neither user 10208 nor current process has android permission
因为手机没有ROOT，不知道root后会不会管用。重启手机无用。

其他信息：
MIUI9 7.10.19开发版
Android 7.1.1
Android 补丁版本 2017-09-01
内核版本 4.4.32-erf-g6a9ee37d-06194-ga7a871e

不知道以上信息是不是够用，我还需要做哪些工作来给予更多信息？谢谢。

**Comment by YueYueYue** [comment]
进一步考察，关闭分应用代理后，就可以正常启动。看来也许是MIUI自己的开发版有兼容性的问题。

**Comment by Akkariiin** [comment]
我对安卓不太熟，希望有能者可以debug进去看看是怎么回事。

**Comment by ashurajo** [comment]
同样这个版本，并没有问题。
@yueyueyue 提供详细日志吧

**Comment by StarryNightL** [comment]
我卸载重装后正常，怀疑是MIUI的问题（我遇到问题的MIUI版本为MIUI9 7.10.19）

**Comment by FishMagic** [comment]
7.10.19非root模式无法正常使用，建议通过BAT

**Comment by YueYueYue** [comment]
@ashurajo 我不知道要如何通过debug调取日志……

**Comment by YueYueYue** [comment]
@StarryNightL 我试过卸载然后重装SSRR，但是并没有用？是不是有什么彻底卸载的方法？

**Comment by YueYueYue** [comment]
@FishMagic 你是说，root后用NAT模式吗？

**Comment by FishMagic** [comment]
@YueYueYue 是的，root后的nat，当时输入法的锅

**Comment by Portan** [comment]
我看网上有人说是分应用不能用，不分的话可以，你们是这样吗？国际版MIUI没有这个问题。

**Comment by FishMagic** [comment]
@Portan  不使用分应用时正常

**Comment by blueboyggh** [comment]
原版ss也有这个问题，所以感觉应该是miui的锅

**Comment by Portan** [comment]
@FishMagic 你试试分应用时不要把SSRR程序排除在外，如果能用，就是说分应用时把SSRR排除出去了

**Comment by FishMagic** [comment]
@Portan 可是我用的是绕行模式呀。。绝对没把SSR或SSRR选中

**Comment by ncs19960831** [comment]
MIUI系统似乎不允许分应用代理，个人感觉应该是网络助手之类的锅，也有可能是MIUI使用了特殊的APP进行流量输出，而分应用代理没有办法找到那个应用

**Comment by silicer** [comment]
同分应用报错，只要不用分应用VPN模式一切正常。NAT可用分应用

**Comment by Akkariiin** [comment]
分应用功能是安卓系统实现的，所以可能是MIUI开发版没有实现这个功能，或者这个功能实现不正确。各位可以向小米官方提issue。【笑

<hr/>

分应用代理功能调用点：

https://github.com/shadowsocksrr/shadowsocksr-android/blob/33162dd8eb29c29870093dd765ef102f20327e7c/src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala#L436-L452

其中的builder是安卓的VpnService的Builder：

https://developer.android.com/reference/android/net/VpnService.Builder.html

**Comment by Akkariiin** [comment]
听说MIUI9正式版发布了，这个问题修复了吗？
@YueYueYue @FishMagic @StarryNightL @ncs19960831

**Comment by KagurasakaAkuryou** [comment]
似乎是由于MIUI的多用户实现方式不正确，导致分应用代理功能不能正确的定位到应用

**Comment by KagurasakaAkuryou** [comment]
似乎移除多用户可以解决这个问题，但是miui没有提供移除多用户的设置选项，目前只能重新刷机解决

**Comment by Akkariiin** [comment]
@KagurasakaAkuryou 噗.....我还在想怎样才能跨多用户提供VPN模式，看来可能不可能了

**Comment by KagurasakaAkuryou** [comment]
今天miui更新的7.11.2修复了这个bug，这个issue可以关了

**Comment by blueboyggh** [comment]
@Akkariiin MIUI并没有正式版的概念，只区分稳定版和开发版，出现这个bug的是10月份的两个开发版，10月份发布的稳定版应该是还没有同步这部分代码，另外因为11.2开发版已经修复了这个bug，所以估计稳定版以后也不会有这个bug了

**Comment by Sak94664** [comment]
如果是6.0的miui，可以试一下quickshortcutmaker，设置>用户，或者直接搜索“用户”，应该就行了。 @KagurasakaAkuryou
