### ISSUE TITLE
安卓9批量测试节点时崩溃

### ISSUE THREAD

**Issue by Andrewshihs** [shadowsocksrr/shadowsocksr-android#223]
批量测试节点时，进行到一半就自动回到主界面，开关也自动关闭了

**Comment by g5239277** [comment]
ssr安卓端很多东西需要更新了，比较直观的关于界面信息都还是原来的。现在节点无法按照名称自动排序，莫名断流等诸多问题已经比较严重，安卓的客户端已经差IOS的第三方一大截了。接手作者也已经弃更，在这反馈也是于事无补，前路不明。

**Comment by AureliusPatiens** [comment]
17个小时之前都还提交了代码?请问你是在哪看到的弃更?

**Comment by AureliusPatiens** [comment]
Akkariiin 昨天也在积极的解决Issues

**Comment by g5239277** [comment]
> Akkariiin 昨天也在积极的解决Issues

不好意思，我非技术人员，只能看到安卓客户端许久未更新，并据此做了回复。现在访问外网是年轻时积累下来的习惯，之前也曾按教程搭建过ss和ssr，但github我一般也只是看到项目界面和问题界面、releases。有想法，欢迎理性讨论。

**Comment by AureliusPatiens** [comment]
> > Akkariiin 昨天也在积极的解决Issues
> 
> 不好意思，我非技术人员，只能看到安卓客户端许久未更新，并据此做了回复。现在访问外网是年轻时积累下来的习惯，之前也曾按教程搭建过ss和ssr，但github我一般也只是看到项目界面和问题界面、releases。有想法，欢迎理性讨论。

github有很多分支,她现在更新的是 Akkariiin 命名开头的分支

**Comment by Andrewshihs** [comment]
@g5239277 超级多小问题，但这个问题在升级9之后出现的，就在这反馈一下。没关注项目进度，顺便问一下，安卓还有其他替代品么？
