### ISSUE TITLE
nat模式下不支持quic(udp)协议

### ISSUE THREAD

**Issue by timwa0669** [shadowsocksrr/shadowsocksr-android#23]
还是说nat模式下不支持udp协议？？

**Comment by Akkariiin** [comment]
nat模式？我没有root的设备来做测试环境所以不清楚。

**Comment by love4taylor** [comment]
NAT 不支持 UDP 转发, 这也就是为什么 NAT 被列为不推荐的原因之一

**Comment by Akkariiin** [comment]
@Love4Taylor 应该是可以支持的吧？

**Comment by love4taylor** [comment]
@Akkariiin 那就得大改了 按路由的套路来 但是 Android 设备的 Kernel 有 tproxy 模块 么

_Sent from my Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
