### ISSUE TITLE
MIUI10国际版 无法使用

### ISSUE THREAD

**Issue by Qionglu735** [shadowsocksrr/shadowsocksr-android#234]
系统： MIUI10 国际版 开发版 
同个wifi下，pc可以连接，android就不行，切4G也无法连接。怀疑是系统的锅，但是完全没头绪……
尝试过各种方法，重启，重装，停google play，都不管用。
有木有大佬遇到这种情况？

**Comment by luo-chuan** [comment]
我的荣耀V20也无法通过SSRR出国了，6月2号之前都还好好的（6月2号我的VPS被封）。今天在Just My Socks上申请了SS账号，然后电脑可以出国（校园网），手机死活出不了国，流量、wifi（校园网）都不行。不知道是不是国内手机厂商配合ZF把SSRR给禁了？

**Comment by OpenHeart123** [comment]
问题同上，我的手机是三星s8，电脑能上，但是手机端用不了，能尽快处理一下这个问题嘛？

**Comment by nanbowaner** [comment]
问题同上

**Comment by Kaijun** [comment]
同样，断流问题...
#90

**Comment by luo-chuan** [comment]
已找到解决方案，只要关闭“UDP转发”，手机就又可以出国了

**Comment by Qionglu735** [comment]
找到问题了
其实是PC上另一个加速器，无意中加速了ssr的流量……
