### ISSUE TITLE
三星 s10, 朋友圈图片加载巨慢

### ISSUE THREAD

**Issue by liximomo** [shadowsocksrr/shadowsocksr-android#237]
路由选的绕过大陆和局域网，微信聊天公众号图片都正常加载，就朋友圈图片加载巨慢，关闭 ssrr 后秒加载。

**Comment by wangpeng119110** [comment]
我的note8也是，以为升级安卓9.0后，ssr断流的问题可以解决，现在看来貌似还是解决不了

**Comment by 417788939** [comment]
> 路由选的绕过大陆和局域网，微信聊天公众号图片都正常加载，就朋友圈图片加载巨慢，关闭 ssrr 后秒加载。

我现在用三星s10+，没发现这个问题，就算挂着ssrr也能正常加载。我估计是梯子服务器问题，如果节点崩了你绕过局域网大陆也不能加载网页。
比如节点服务商设置了黑名单什么的。

**Comment by Aitozi** [comment]
oneplus 7 pro 也碰到一样的问题，开启ssr（仅代理中国大陆无法访问地址）打开朋友圈图片很慢

**Comment by liximomo** [comment]
换成 ss 了， 没有此问题。

**Comment by jswing0818** [comment]
我的也是这样的情况，一关ssrr就秒加载。好奇怪

**Comment by yichen98741** [comment]
各位大神这个问题解决了吗？我也是一样 我用MIUI 开ssrr后也是微信朋友圈图片加载特慢 小视频其他没问题？ 如果已经解决麻烦分享一下方法 谢谢

**Comment by 6Weiqi** [comment]
把 UDP 转发关了就行

**Comment by Aitozi** [comment]
> 把 UDP 转发关了就行

我没有开UDP转发，一样有朋友圈图片加载慢的问题

**Comment by yichen98741** [comment]
我刚关了 还是一样的 梯子的问题 但不知道哪里

**Comment by Aitozi** [comment]
可以使用ssr的分应用代理的功能，设置微信不走代理，就可以解决这个问题，亲测有效

**Comment by yichen98741** [comment]
确实有效，谢谢了。
