### ISSUE TITLE
远程dns和代理服务器相同ip时不支持其他端口除53

### ISSUE THREAD

**Issue by timwa0669** [shadowsocksrr/shadowsocksr-android#24]
这个状况在开启了转发udp时会出现这个问题，不开启转发udp则没有这个问题。

**Comment by MichaelHu55** [comment]
如果你转发了udp，我的测试是，直接无视了dns设置。dns设置全删，或者乱改，都一样没有问题。

**Comment by Akkariiin** [comment]
@MichaelHu55  开了udp转发，所有udp包都会被直接转发，包括dns查询包。

可以参照[这篇](http://ct2wj.com/2016/02/28/shadowsocks-android-source-code-analysis/)去读安卓源码
