### ISSUE TITLE
微信朋友圈加载图片视频很慢

### ISSUE THREAD

**Issue by 7990062** [shadowsocksrr/shadowsocksr-android#248]
微信朋友圈加载图片视频很慢
不管是绕过局域网和大陆，还是只代理被墙，或者开启分应用代理都一样
其他应用有些也有不同程度影响，有些正常，有些是局部图片加载慢
关闭SSRR之后，秒开，正常
使用SS也正常加载！
不知道有没有大佬能解决？

**Comment by HaHaIsMe** [comment]
这种情况一般是DNS的问题，查检一下DNS的配置……

7990062 <notifications@github.com> 于2019年8月4日周日 上午9:33写道：

**Comment by AdoShan** [comment]
是改软件里面的哪个DNS？软件里面有China DNS还有DNS两个选项。反正我都是默认的。没改过
China DNS的值为114.114.114.114：53，223.5.5.5：53，DNS的值为208.67.222.222：53

**Comment by frankfanio** [comment]
我昨天也遇到了这个问题，症状和你一模一样，票圈图片加载慢，然后关了SSR秒加载。摸索了一下SSR的配置之后貌似解决了：
代理规则：绕过局域网及中国大陆
分应用代理：开启，里面的“绕行模式”是关闭的，然后选中Chrome、YouTube、Gmail等需要代理的应用即可
经过测试，YoTube应用等正常富强，Chrome中的YouTube网页版正常富强，利用myip.ipip.net查看当前IP时显示的是未富强的IP，说明还是按照代理规则来的，即国内IP不走SSR

另外还有一个小修改，将DNS改成了和SS安卓客户端一样的配置：8.8.8.8（ChinaDNS未修改）

可以试一下 @7990062

**Comment by baixiaodong** [comment]
亲测，ffffansz提供的方法完美解决，不过我没改dns也可以的

**Comment by llerer** [comment]
> 微信朋友圈加载图片视频很慢
> 不管是绕过局域网和大陆，还是只代理被墙，或者开启分应用代理都一样
> 其他应用有些也有不同程度影响，有些正常，有些是局部图片加载慢
> 关闭SSRR之后，秒开，正常
> 使用SS也正常加载！
> 不知道有没有大佬能解决？

路由选全局，打开分应用代理，默认关闭绕行模式，然后选择你需要走代理的那些APP即可。按此方法设置后，微信票圈图片秒加载。亲测有效。

**Comment by ghost** [comment]
> > 微信朋友圈加载图片视频很慢
> > 不管是绕过局域网和大陆，还是只代理被墙，或者开启分应用代理都一样
> > 其他应用有些也有不同程度影响，有些正常，有些是局部图片加载慢
> > 关闭SSRR之后，秒开，正常
> > 使用SS也正常加载！
> > 不知道有没有大佬能解决？
> 
> 路由选全局，打开分应用代理，默认关闭绕行模式，然后选择你需要走代理的那些APP即可。按此方法设置后，微信票圈图片秒加载。亲测有效。

还是有些不方便，浏览器有时候上国内外网站就有些不方便，搞不懂为什么ss客户端没啥影响。

**Comment by frankfanio** [comment]
> > > 微信朋友圈加载图片视频很慢
> > > 不管是绕过局域网和大陆，还是只代理被墙，或者开启分应用代理都一样
> > > 其他应用有些也有不同程度影响，有些正常，有些是局部图片加载慢
> > > 关闭SSRR之后，秒开，正常
> > > 使用SS也正常加载！
> > > 不知道有没有大佬能解决？
> > 
> > 
> > 路由选全局，打开分应用代理，默认关闭绕行模式，然后选择你需要走代理的那些APP即可。按此方法设置后，微信票圈图片秒加载。亲测有效。
> 
> 还是有些不方便，浏览器有时候上国内外网站就有些不方便，搞不懂为什么ss客户端没啥影响。

因为SS走的是PAC，是按照域名过滤的。你把浏览器也加到分应用代理列表里，然后代理模式选择绕过局域网和大陆，亲测国内网站还是直连的，用ipip.net测过，国外网站走的就是代理

**Comment by ghost** [comment]
> > > > 微信朋友圈加载图片视频很慢
> > > > 不管是绕过局域网和大陆，还是只代理被墙，或者开启分应用代理都一样
> > > > 其他应用有些也有不同程度影响，有些正常，有些是局部图片加载慢
> > > > 关闭SSRR之后，秒开，正常
> > > > 使用SS也正常加载！
> > > > 不知道有没有大佬能解决？
> > > 
> > > 
> > > 路由选全局，打开分应用代理，默认关闭绕行模式，然后选择你需要走代理的那些APP即可。按此方法设置后，微信票圈图片秒加载。亲测有效。
> > 
> > 
> > 还是有些不方便，浏览器有时候上国内外网站就有些不方便，搞不懂为什么ss客户端没啥影响。
> 
> 因为SS走的是PAC，是按照域名过滤的。你把浏览器也加到分应用代理列表里，然后代理模式选择绕过局域网和大陆，亲测国内网站还是直连的，用ipip.net测过，国外网站走的就是代理

好的，谢谢大佬

**Comment by formuladizi** [comment]
非常感谢
