### ISSUE TITLE
什么反人类设计 端口号那个

### ISSUE THREAD

**Issue by dqt19921207** [shadowsocksrr/shadowsocksr-android#254]

**Comment by hedroid** [comment]
自己弱智，来这里喷粪。能滚多远滚多远。垃圾。

> 草泥马的 几万个端口用滚轮？？？什么鬼才设计思路？？？还特么更新了这么多版本？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by boris1993** [comment]
可以直接输入

**Comment by 1c383r9** [comment]
怕是没脑子

**Comment by boris1993** [comment]
@shadowsocksrr plz help close this issue.

**Comment by pluieciel** [comment]
@boris1993 求问怎么输入？谢谢

**Comment by pluieciel** [comment]
会了...数字太小了，点几次没点到没反应，还以为不能点...

**Comment by thevirtualsystems** [comment]
点一下即可输入
