### ISSUE TITLE
无法调用自带的相机扫描二维码！

### ISSUE THREAD

**Issue by 1990chs** [shadowsocksrr/shadowsocksr-android#26]
RT，在扫描二维码的时候，点击“扫描二维码”没反应，不知道怎么回事！

**Comment by Portan** [comment]
我重装了系统后就可以使用了，你可以试下……

**Comment by Akkariiin** [comment]
https://github.com/shadowsocksrr/shadowsocksr-android/releases/tag/3.5.1.1
试试自带扫描器版本  : )

**Comment by Akkariiin** [comment]
另外，检查是否授权了相机权限

**Comment by 1990chs** [comment]
@Akkariiin 一直没收到邮件提醒，以为没有回答，使用了扫描版本还不行，权限我设置信任也不行！

**Comment by Akkariiin** [comment]
@1990chs 是不是你的系统环境问题？自己检查一下吧？

**Comment by 1990chs** [comment]
不知道，先这样凑活着用吧！谢谢！
