### ISSUE TITLE
请求在顶部下拉菜单中增加开关SSR的按钮

### ISSUE THREAD

**Issue by frankfanio** [shadowsocksrr/shadowsocksr-android#262]
\# Enhancement

请问可否麻烦作者跟进一下隔壁SS客户端的改进，即在顶部下拉菜单中增加SSR的按钮，如下图所示
![image](https://user-images.githubusercontent.com/18579977/65015254-919cdc00-d953-11e9-9bde-49f95470d1be.png)
这样开启和关闭代理会方便很多~

**Comment by pjy612** [comment]
这个不是有吗？

**Comment by frankfanio** [comment]
> 这个不是有吗？

诶 是要在哪里开启吗？直接安装没有自动添加进去啊
ps: 我截图的这个是ss的，不是ssr的

**Comment by pjy612** [comment]
华为 麦芒5 分配顶部下拉按钮时 能找到 一个 叫 SSR的 图标 用法和 SS是差不多的。
不清楚其他 安卓系统 是否一样...
你试试 齿轮旁边的按钮 点击后 是否有 多的 按钮可选

**Comment by frankfanio** [comment]
> 华为 麦芒5 分配顶部下拉按钮时 能找到 一个 叫 SSR的 图标 用法和 SS是差不多的。
> 不清楚其他 安卓系统 是否一样...
> 你试试 齿轮旁边的按钮 点击后 是否有 多的 按钮可选

找到了！感谢🙏 好久之前装的ss 已经忘记这个原来是这么加进去的
