### ISSUE TITLE
Android 10 停止SSRR后 无法自动断开VPN

### ISSUE THREAD

**Issue by pjy612** [shadowsocksrr/shadowsocksr-android#268]
Android 10 停止SSRR后 无法自动断开VPN。
需要去VPN列表手动断开连接。
SS 直接就不能用，连上也不能用。

**Comment by haige268** [comment]
Android 10上还是可以用的吧，只是有这个小BUG对吧

**Comment by pjy612** [comment]
> Android 10上还是可以用的吧，只是有这个小BUG对吧

现在已经好了，可能是华为自己的UI问题。
后面更新了一次就好了
