### ISSUE TITLE
华为 Mate 30 断开连接失效，必须杀死才能断开连接

### ISSUE THREAD

**Issue by songispm** [shadowsocksrr/shadowsocksr-android#272]
如题，软件环境 ：EMUI10 （Android 10），点击软件内的 按钮，打开连接没有问题，但再次无法断开

**Comment by imkodo** [comment]
必须要去VPN里把VPN断开才行

**Comment by 417788939** [comment]
是保时捷吗？大佬能否给个联系方式(✪ω✪)

**Comment by realgu** [comment]
这个问题很简单，因为华为后台杀进程了。你设置一下后台进程。我就是mate30。

**Comment by yyaok858759001** [comment]
如何设置后台进程呢

**Comment by songispm** [comment]
> 这个问题很简单，因为华为后台杀进程了。你设置一下后台进程。我就是mate30。

正解，得设置一下 权限管理，和系统电池自动省电优化，此 issue 关闭
