### ISSUE TITLE
想更新下端口发现购买页面被我弄丢了

### ISSUE THREAD

**Issue by w825735810** [shadowsocksrr/shadowsocksr-android#276]
求一个购买页面我真的自己把自己气笑了hhh

**Comment by w825735810** [comment]
![IMG_20191213_154910](https://user-images.githubusercontent.com/58842085/70780715-22068380-1dc0-11ea-97eb-8f9540776306.jpg)
这是我的购买付款记录

**Comment by FlyingStarlight** [comment]
这个软件只是个软件，没有出售过任何节点也没有直接提供任何服务的，你搞错地方了
