### ISSUE TITLE
希望尽快适配安卓8.0

### ISSUE THREAD

**Issue by FanhuaCloud** [shadowsocksrr/shadowsocksr-android#28]
更新安卓8.0之后shadowsocksrr在后台运行会显示SSRR正在运行，希望能尽快适配

**Comment by Akkariiin** [comment]
难道不应该在任务栏显示`SSRR正在运行`吗？可以给一个截图看看吗？

**Comment by MichaelHu55** [comment]
显示正在运行和ssrr是无关的。这是oreo的特性。你需要去play下载Hide "running in the background" Notification
安装运行这个应用就可以了。这个issue可以关了

**Comment by FanhuaCloud** [comment]
好的感谢
