### ISSUE TITLE
mac上build.sh执行结果，求教

### ISSUE THREAD

**Issue by txdywy** [shadowsocksrr/shadowsocksr-android#29]
[armeabi-v7a] Compile thumb  : ancillary <= fd_recv.c
[armeabi-v7a] Compile thumb  : ancillary <= fd_send.c
[armeabi-v7a] Compile thumb  : proxychains4 <= version.c
[armeabi-v7a] Compile thumb  : proxychains4 <= core.c
[armeabi-v7a] Compile thumb  : proxychains4 <= common.c
4 warnings generated.
[armeabi-v7a] Compile thumb  : proxychains4 <= libproxychains.c
[armeabi-v7a] Compile thumb  : proxychains4 <= allocator_thread.c
jni/proxychains/src/libproxychains.c:483:17: error: conflicting types for 'gethostbyaddr'
struct hostent *gethostbyaddr(const char *addr, int len, int type) {
                ^
/usr/local/Caskroom/android-ndk/15c/android-ndk-r15c/sysroot/usr/include/netdb.h:204:17: note: previous
      declaration is here
struct hostent* gethostbyaddr(const void*, socklen_t, int);
                ^
1 error generated.

**Comment by Akkariiin** [comment]
ndk版本太高，看readme

**Comment by txdywy** [comment]
这个后来下载ndk12确实解决了。不过很奇怪，后来在另一台mac上用brew安装的15也没问题了。

**Comment by Akkariiin** [comment]
gethostbyaddr的接口声明改了
去看代码你就明白是怎么回事

**Comment by txdywy** [comment]
原来如此😯
