### ISSUE TITLE
auth_chain_c  auth_chain_d支持

### ISSUE THREAD

**Issue by wclmgcd** [shadowsocksrr/shadowsocksr-android#3]
破酱娃的SSR都只有auth_chain_a   auth_chain_b，auth_chain_c auth_chain_d是哪位又接着更新ssr了吗

**Comment by shadowxr** [comment]
？？？
接手支持呀。
ssrr这个项目不就是Akkariin接手更新的么

**Comment by wclmgcd** [comment]
能给个网址吗？没找到，感谢

**Comment by ghost** [comment]
https://github.com/shadowsocksrr/shadowsocksr

作者 https://github.com/Akkariiin
