### ISSUE TITLE
为何sbt执行时import不了这些包？

### ISSUE THREAD

**Issue by txdywy** [shadowsocksrr/shadowsocksr-android#30]
[info] Processing resources
[info] QueuedCruncher is using /usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/aapt
[warn] warning: string 'kcp_port' has no default translation.
[warn] warning: string 'kcp_port_summary' has no default translation.
[warn] warning: string 'kcp_summary' has no default translation.
[warn] warning: string 'kcpcli' has no default translation.
[warn] warning: string 'remote_dns' has no default translation.
[warn] warning: string 'remote_dns_summary' has no default translation.
[info] Rebuilding all classes because R.java has changed
[info] Compiling 46 Scala sources and 22 Java sources to /Users/yiwei/shadowsocksr-android/target/scala-2.11/classes...
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ShadowsocksApplication.scala:63: not found: object eu
[error] import eu.chainfire.libsuperuser.Shell
[error]        ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/utils/TcpFastOpen.scala:5: not found: object eu
[error] import eu.chainfire.libsuperuser.Shell
[error]        ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ScannerActivity.scala:17: object ZXingScannerView is not a member of package me.dm7.barcodescanner.zxing
[error] import me.dm7.barcodescanner.zxing.ZXingScannerView
[error]        ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ScannerActivity.scala:23: not found: value ZXingScannerView
[error] class ScannerActivity extends AppCompatActivity with ZXingScannerView.ResultHandler {
[error]                                                      ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ScannerActivity.scala:26: not found: type ZXingScannerView
[error]   private var scannerView: ZXingScannerView = _
[error]                            ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ScannerActivity.scala:59: not found: type ZXingScannerView
[error]     scannerView = findViewById(R.id.scanner).asInstanceOf[ZXingScannerView]

**Comment by txdywy** [comment]
貌似import不了的都是aar的？

**Comment by Akkariiin** [comment]
有设置代理吗，请仔细参照readme。

https://github.com/shadowsocksrr/shadowsocksr-android/blob/Akkariiin/master/README.md

**Comment by txdywy** [comment]
之前在家里电脑和单位都成功过，是尝试用proxychain的命令行套sbt走代理。单位现在试了很多次都报这个。试试设置一下java代理看看。

**Comment by txdywy** [comment]
➜  shadowsocksr-android git:(Akkariiin/develop) ✗ sbt run
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading project definition from /Users/yiwei/shadowsocksr-android/project
[info] Set current project to shadowsocksr (in build file:/Users/yiwei/shadowsocksr-android/)
[warn] /Users/yiwei/shadowsocksr-android/src/main/AndroidManifest.xml:20:5-21:45 Warning:
[warn] 	Element uses-feature#android.hardware.camera at AndroidManifest.xml:20:5-21:45 duplicated with element declared at AndroidManifest.xml:14:5-15:45
[info] Compiling 46 Scala sources and 22 Java sources to /Users/yiwei/shadowsocksr-android/target/scala-2.11/classes...
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ShadowsocksApplication.scala:63: not found: object eu
[error] import eu.chainfire.libsuperuser.Shell
[error]        ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/utils/TcpFastOpen.scala:5: not found: object eu
[error] import eu.chainfire.libsuperuser.Shell
[error]        ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ScannerActivity.scala:17: object ZXingScannerView is not a member of package me.dm7.barcodescanner.zxing
[error] import me.dm7.barcodescanner.zxing.ZXingScannerView
[error]        ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ScannerActivity.scala:23: not found: value ZXingScannerView
[error] class ScannerActivity extends AppCompatActivity with ZXingScannerView.ResultHandler {
[error]                                                      ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ScannerActivity.scala:26: not found: type ZXingScannerView
[error]   private var scannerView: ZXingScannerView = _
[error]                            ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ScannerActivity.scala:59: not found: type ZXingScannerView
[error]     scannerView = findViewById(R.id.scanner).asInstanceOf[ZXingScannerView]
[error]                                                           ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala:55: not found: object eu
[error] import eu.chainfire.libsuperuser.Shell
[error]        ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala:76: not found: value Shell
[error]   var su: Shell.Interactive = _
[error]           ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala:345: not found: value Shell
[error]     su = new Shell.Builder().useSU().setWantSTDERR(true).setWatchdogTimeout(10).open((_, exitCode, _) =>
[error]              ^
[warn] Class net.vrallev.android.cat.CatLog not found - continuing with a stub.
[warn] Class net.vrallev.android.cat.CatLog not found - continuing with a stub.
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ShadowsocksApplication.scala:233: not found: value Shell
[error]       val result = Shell.SU.run(cmd.toArray)
[error]                    ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ShadowsocksApplication.scala:236: not found: value Shell
[error]     Shell.SH.run(cmd.toArray)
[error]     ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/ShadowsocksApplication.scala:243: not found: value Shell
[error]     Shell.SH.run(EXECUTABLES.map("chmod 755 " + getApplicationInfo.dataDir + '/' + _))
[error]     ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/utils/TaskerSettings.scala:45: object twofortyfouram is not a member of package com
[error] import com.twofortyfouram.locale.api.{Intent => ApiIntent}
[error]            ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/utils/TaskerSettings.scala:65: not found: value ApiIntent
[error]     new Intent().putExtra(ApiIntent.EXTRA_BUNDLE, bundle).putExtra(ApiIntent.EXTRA_STRING_BLURB,
[error]                           ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/utils/TaskerSettings.scala:65: not found: value ApiIntent
[error]     new Intent().putExtra(ApiIntent.EXTRA_BUNDLE, bundle).putExtra(ApiIntent.EXTRA_STRING_BLURB,
[error]                                                                    ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/utils/TaskerSettings.scala:51: not found: value ApiIntent
[error]   def fromIntent(intent: Intent) = new TaskerSettings(if (intent.hasExtra(ApiIntent.EXTRA_BUNDLE))
[error]                                                                           ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/utils/TaskerSettings.scala:52: not found: value ApiIntent
[error]     intent.getBundleExtra(ApiIntent.EXTRA_BUNDLE) else Bundle.EMPTY)
[error]                           ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/utils/TcpFastOpen.scala:32: not found: value Shell
[error]     val suAvailable = Shell.SU.available();
[error]                       ^
[error] /Users/yiwei/shadowsocksr-android/src/main/scala/com/github/shadowsocks/utils/TcpFastOpen.scala:34: not found: value Shell
[error]       val res = Shell.run("su", Array(
[error]                 ^
[warn] two warnings found
[error] 19 errors found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 8 s, completed Nov 2, 2017 9:23:23 AM



设置了java代理。

➜  ~ cd .ivy2 
➜  .ivy2 ls
cache
➜  .ivy2 cd cache 
➜  cache ls
com.android.databinding                 com.github.julien-truffaut              com.mikepenz                            net.jcip                                org.javassist
com.android.support                     com.github.mdr                          com.squareup                            net.orfjackal.retrolambda               org.json4s
com.android.tools                       com.google                              com.squareup.okhttp3                    net.sf.jopt-simple                      org.ow2
com.android.tools.analytics-library     com.google.android.gms                  com.squareup.okio                       net.sf.kxml                             org.ow2.asm
com.android.tools.build                 com.google.code.findbugs                com.thoughtworks.paranamer              net.sf.proguard                         org.scala-lang
com.android.tools.ddms                  com.google.code.gson                    com.twofortyfouram                      net.vrallev.android                     org.scala-lang.modules
com.android.tools.external.com-intellij com.google.guava                        commons-codec                           org.antlr                               org.scala-sbt
com.android.tools.external.lombok       com.google.jimfs                        commons-io                              org.apache                              org.scala-sbt.ivy
com.android.tools.jack                  com.google.protobuf                     commons-logging                         org.apache.commons                      org.scala-tools.sbinary
com.android.tools.jill                  com.google.zxing                        dnsjava                                 org.apache.httpcomponents               org.scalamacros
com.android.tools.layoutlib             com.googlecode.juniversalchardet        eu.chainfire                            org.bouncycastle                        org.scalaz
com.android.tools.lint                  com.hanhuy.sbt                          io.argonaut                             org.codehaus                            org.sonatype.oss
com.evernote                            com.intellij                            jline                                   org.eclipse.jdt.core.compiler           org.spire-math
com.github.clans                        com.j256.ormlite                        me.dm7.barcodescanner                   org.fusesource.jansi                    org.typelevel
com.github.jorgecastilloprz             com.jcraft                              net.glxn.qrgen                          org.jacoco                              scala_2.10
➜  cache 
看cache里这些包也下载了，都是aar的不能import？

**Comment by txdywy** [comment]
这个可以怎么调试吗？刚接触scala+sbt，很困惑哦😪

**Comment by Akkariiin** [comment]
我也不知道

**Comment by txdywy** [comment]
目前确认在resolver步骤是最终把包下载到了.ivy2目录，不过dependencyClasspath里面是没有的。原因待查

> show compile:dependencyClasspath
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-cardview-v7-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-design-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-appcompat-v7-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-support-vector-drawable-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-animated-vector-drawable-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-recyclerview-v7-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-transition-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-gridlayout-v7-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-preference-v14-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-preference-v7-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.evernote-android-job-1.1.3/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.github.clans-fab-1.6.4/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.github.jorgecastilloprz-fabprogresscircle-1.01/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-analytics-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-analytics-impl-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-base-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-basement-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-tasks-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-tagmanager-v4-impl-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-gcm-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-iid-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.mikepenz-fastadapter-2.1.5/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.mikepenz-iconics-core-2.8.2/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.mikepenz-materialdrawer-5.8.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.mikepenz-materialize-1.0.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-support-v4-25.3.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-support-compat-25.3.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-support-media-compat-25.3.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-support-core-utils-25.3.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-support-core-ui-25.3.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-support-fragment-25.3.1/classes.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.j256.ormlite/ormlite-android/jars/ormlite-android-5.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.j256.ormlite/ormlite-core/jars/ormlite-core-5.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/net.jcip/jcip-annotations/jars/jcip-annotations-1.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/dnsjava/dnsjava/jars/dnsjava-2.1.7.jar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/support-annotations/25.3.1/support-annotations-25.3.1.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.google.zxing/core/jars/core-3.3.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/net.glxn.qrgen/android/jars/android-2.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/net.glxn.qrgen/core/jars/core-2.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.squareup.okhttp3/okhttp/jars/okhttp-3.8.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.squareup.okio/okio/jars/okio-1.13.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-1.3.9.jar)
[success] Total time: 0 s, completed Nov 7, 2017 2:58:31 PM

**Comment by txdywy** [comment]
在build.sbt里加上classpathTypes += "aar" 如下有了，但是compile报错没变

有点像这里碰到的问题https://stackoverflow.com/questions/29022678/dependency-missing-from-classpath


> show compile:dependencyClasspath
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-cardview-v7-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-design-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-appcompat-v7-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-support-vector-drawable-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-animated-vector-drawable-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-recyclerview-v7-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-transition-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-gridlayout-v7-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-preference-v14-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-preference-v7-25.1.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.evernote-android-job-1.1.3/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.github.clans-fab-1.6.4/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.github.jorgecastilloprz-fabprogresscircle-1.01/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-analytics-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-analytics-impl-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-base-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-basement-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-tasks-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-tagmanager-v4-impl-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-gcm-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.google.android.gms-play-services-iid-10.0.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.mikepenz-fastadapter-2.1.5/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.mikepenz-iconics-core-2.8.2/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.mikepenz-materialdrawer-5.8.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.mikepenz-materialize-1.0.0/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-support-v4-25.3.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-support-compat-25.3.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-support-media-compat-25.3.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-support-core-utils-25.3.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-support-core-ui-25.3.1/classes.jar)
[info] * Attributed(/Users/yiwei/.android/sbt/exploded-aars/com.android.support-support-fragment-25.3.1/classes.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8.jar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/cardview-v7/25.1.0/cardview-v7-25.1.0.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/design/25.1.0/design-25.1.0.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/support-vector-drawable/25.1.0/support-vector-drawable-25.1.0.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/animated-vector-drawable/25.1.0/animated-vector-drawable-25.1.0.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/recyclerview-v7/25.1.0/recyclerview-v7-25.1.0.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/transition/25.1.0/transition-25.1.0.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/gridlayout-v7/25.1.0/gridlayout-v7-25.1.0.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/preference-v14/25.1.0/preference-v14-25.1.0.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/preference-v7/25.1.0/preference-v7-25.1.0.aar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.evernote/android-job/aars/android-job-1.1.3.aar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/net.vrallev.android/cat/aars/cat-1.0.5.aar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.github.clans/fab/aars/fab-1.6.4.aar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.github.jorgecastilloprz/fabprogresscircle/aars/fabprogresscircle-1.01.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/google/m2repository/com/google/android/gms/play-services-analytics/10.0.1/play-services-analytics-10.0.1.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/google/m2repository/com/google/android/gms/play-services-analytics-impl/10.0.1/play-services-analytics-impl-10.0.1.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/google/m2repository/com/google/android/gms/play-services-base/10.0.1/play-services-base-10.0.1.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/google/m2repository/com/google/android/gms/play-services-basement/10.0.1/play-services-basement-10.0.1.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/google/m2repository/com/google/android/gms/play-services-tasks/10.0.1/play-services-tasks-10.0.1.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/google/m2repository/com/google/android/gms/play-services-tagmanager-v4-impl/10.0.1/play-services-tagmanager-v4-impl-10.0.1.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/google/m2repository/com/google/android/gms/play-services-gcm/10.0.1/play-services-gcm-10.0.1.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/google/m2repository/com/google/android/gms/play-services-iid/10.0.1/play-services-iid-10.0.1.aar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.j256.ormlite/ormlite-android/jars/ormlite-android-5.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.j256.ormlite/ormlite-core/jars/ormlite-core-5.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.mikepenz/fastadapter/aars/fastadapter-2.1.5.aar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.mikepenz/iconics-core/aars/iconics-core-2.8.2.aar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.mikepenz/materialdrawer/aars/materialdrawer-5.8.1.aar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.mikepenz/materialize/aars/materialize-1.0.0.aar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.twofortyfouram/android-plugin-api-for-locale/aars/android-plugin-api-for-locale-1.0.2.aar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/net.jcip/jcip-annotations/jars/jcip-annotations-1.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/dnsjava/dnsjava/jars/dnsjava-2.1.7.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/eu.chainfire/libsuperuser/aars/libsuperuser-1.0.0.201704021214.aar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/me.dm7.barcodescanner/zxing/aars/zxing-1.9.8.aar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/me.dm7.barcodescanner/core/aars/core-1.9.8.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/support-v4/25.3.1/support-v4-25.3.1.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/support-compat/25.3.1/support-compat-25.3.1.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/support-annotations/25.3.1/support-annotations-25.3.1.jar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/support-media-compat/25.3.1/support-media-compat-25.3.1.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/support-core-utils/25.3.1/support-core-utils-25.3.1.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/support-core-ui/25.3.1/support-core-ui-25.3.1.aar)
[info] * Attributed(/usr/local/Caskroom/android-sdk/3859397,26.0.2/extras/android/m2repository/com/android/support/support-fragment/25.3.1/support-fragment-25.3.1.aar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.google.zxing/core/jars/core-3.3.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/net.glxn.qrgen/android/jars/android-2.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/net.glxn.qrgen/core/jars/core-2.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.squareup.okhttp3/okhttp/jars/okhttp-3.8.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.squareup.okio/okio/jars/okio-1.13.0.jar)
[info] * Attributed(/Users/yiwei/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-1.3.9.jar)
[success] Total time: 0 s, completed Nov 7, 2017 3:35:25 PM

**Comment by txdywy** [comment]
最后发现问题了，就是aar的包在下载部署时出了问题
It's also possible that somehow the contents of the aar were corrupted. It should automatically fix itself, but if you're running an old version of sbt-android it won't. 

解决办法
In that case rm -r ~/. android/sbt/exploded-aars
