### ISSUE TITLE
前置代理的地址栏支持输入域名

### ISSUE THREAD

**Issue by huppyuy** [shadowsocksrr/shadowsocksr-android#31]
能否让前置代理的地址栏支持域名输入？现在输入域名会在日志里面显示地址不是数字。
另外能否将前置代理与代理服务器分离开来？就是不需要输入SS的代理服务器 也可以开启前置代理。十分感谢，好人！

**Comment by Akkariiin** [comment]
`另外能否将前置代理与代理服务器分离开来？就是不需要输入SS的代理服务器 也可以开启前置代理。`
这功能随便哪个socks5客户端都可以实现，为什么一定要SS来做呢？

**Comment by huppyuy** [comment]
但是可以分应用代理的我没有找到，你有推荐的吗？

**Comment by Akkariiin** [comment]
@huppyuy 我没用过类似的软件，不是太清楚。
