### ISSUE TITLE
pdnsd 访问其启动命令中指定的配置文件时出现权限问题

### ISSUE THREAD

**Issue by Crystal-RainSlide** [shadowsocksrr/shadowsocksr-android#32]
11-04 19:52:44.721 I/ForkJoinPool-1-(10398): type=1400 audit(0.0:5869): avc: denied { open } for path="/data/data/in.zhaoj.shadowsocksrr/pdnsd-vpn.conf" dev="dm-0" ino=131173 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:app_data_file:s0 tclass=file permissive=1

手动设置为 全部组可读写 rw-rw-rw- 之后，依旧如此

pdnsd 自身却只提示找不到 pdnsd.cache 文件，手动创建设置权限后解决

（一时没有其他设备可供测试，不知是否是系统导致的个别问题，如果无法复现上面那样的log的话，还请谅解…）

**Comment by Akkariiin** [comment]
pdnsd-vpn.conf 这个文件是动态创建的。

https://github.com/shadowsocksrr/shadowsocksr-android/blob/33162dd8eb29c29870093dd765ef102f20327e7c/src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala#L344-L415

L407、L410

如果你的系统很特别或者root后设置了特别的权限系统。可能需要对应地做一些设置。
如果暂时解决不了的话，可以开启UDP转发，这个模式不会启动pdnsd，但是可能会更容易受到远程dns网络不稳定的影响。

**Comment by Crystal-RainSlide** [comment]
收到，感谢帮助

**Comment by Akkariiin** [comment]
如果你是小米系统，我猜可能需要修改selinux的相关配置（笑

**Comment by Crystal-RainSlide** [comment]
我 RR 6.0.1，而且系统的SELinux开关没坏……

**Comment by Akkariiin** [comment]
@Crystal-RainSlide 那我就不太清楚了，貌似小米系统之前出了几个类似的问题。
