### ISSUE TITLE
建议将国内 DNS 改为 119.29.29.29

### ISSUE THREAD

**Issue by zmz125000** [shadowsocksrr/shadowsocksr-android#34]
114DNS 干的坏事已经被扒皮了。

**Comment by ustczzh** [comment]
有什么问题么？没有搜到。

**Comment by zmz125000** [comment]
https://luojia.me/2015/07/14/114dns%E5%88%B0%E5%BA%95%E6%98%AF%E5%95%A5/

**Comment by birdofprey** [comment]
原来实名制确实很有好处。哈哈哈。。。

**Comment by birdofprey** [comment]
技术人员要防止自己成为被抛弃的白手套。。。

**Comment by birdofprey** [comment]
这个DNS是什么情况呢？？

**Comment by Justsoos** [comment]
国内自建的无污染 dns 很少有特别稳定的，尤其是对国内网站 cdn 分流支持非常差，只能说，自己试试吧

**Comment by BROBIRD** [comment]
能不能不要把面向运营商的商业服务和面向普通网民的免费公共服务混为一谈？

> 不要见得风是得雨，总想搞个大新闻

批判之前请拿出足够硬的直接证据。
