### ISSUE TITLE
是否支持旧版本的安卓系统（android4.0）？

### ISSUE THREAD

**Issue by a421809265** [shadowsocksrr/shadowsocksr-android#36]
以前的老平板系统是android4.0 icecrem，
安装这个安卓客户端时老是提示解析包错误，不知道是不是因为不兼容旧版本，特来请教怎么解决的？

**Comment by Akkariiin** [comment]
我的测试设备最低只有6.0
有谁有4的设备可以提供反馈吗

**Comment by Qixingchen** [comment]
https://github.com/shadowsocksrr/shadowsocksr-android/blob/Akkariiin/master/src/main/AndroidManifest.xml#L24 

min sdk 16 means support 4.1(JELLY_BEAN) and above

**Comment by a421809265** [comment]
THX A LOT!

2017-11-15 9:47 GMT+08:00 qixingchen <notifications@github.com>:

**Comment by a421809265** [comment]
我的旧手机4.0的不行的，低版本的装不上，

2017-11-20 12:39 GMT+08:00 Akkariiin <notifications@github.com>:
