### ISSUE TITLE
建议设置开启转发UDP时不转发China DNS选项里的IP地址

### ISSUE THREAD

**Issue by timwa0669** [shadowsocksrr/shadowsocksr-android#39]
建议设置开启转发UDP时不转发China DNS选项里的IP地址，加一下这个功能吧。

**Comment by Akkariiin** [comment]
??????

**Comment by timwa0669** [comment]
开启udp转发时会同时转发china dns(example : 119.29.29.29:53)，实际上这个ip不需要转发，可以加入不代理名单。

**Comment by Akkariiin** [comment]
开启UDP转发时会转发所有UDP包，并且China DNS无效。
China DNS是给不开启UDP转发模式时的本地DNS服务器用的。
参见源码及这篇文章

http://ct2wj.com/2016/02/28/shadowsocks-android-source-code-analysis/
