### ISSUE TITLE
ssr订阅怎么不能添加啊，删除自带的也会重新出现

### ISSUE THREAD

**Issue by j4Uq** [shadowsocksrr/shadowsocksr-android#4]
目前是最新版ssr-android3.5.1，添加的[订阅地址]()，pc版正常使用，但到了安卓版却怎么也添加不进去

**Comment by Akkariiin** [comment]
在有其他服务器的时候，删除自带订阅带来的服务器就不会重新出现了。
至于为什么添加不了，暂不清楚。

**Comment by shadowxr** [comment]
我的都是能添加的，解码看了下你的，格式有问题，不知道是不是原因

**Comment by j4Uq** [comment]
@shadowxr 什么格式有问题?

**Comment by Akkariiin** [comment]
@523860169 应该是链接内容的编码格式问题，这个问题你需要给提供这个订阅地址的管理者提issue来解决。

**Comment by j4Uq** [comment]
@Akkariiin 额，就是我自己弄了个shell脚本搞得订阅地址，然而并不知道怎么搞编码

**Comment by Akkariiin** [comment]
脚本有问题？？？贴出来看看

**Comment by shadowxr** [comment]
我记得原作者在规定的相关格式，不过我没看。
所以不太知道正确的格式
不过我解码对比你的和正常能添加的

你的链接一次解码后
前面多出
MAX=10

ssr相关链接后多出一到两个=

不知道是不是原因

**Comment by Akkariiin** [comment]
@shadowxr 记得要去掉末尾的=

**Comment by Akkariiin** [comment]
要去链接末尾的`=`但不去掉订阅末尾的
见下
https://github.com/shadowsocksrr/shadowsocks-rss/wiki/SSR-QRcode-scheme

https://github.com/shadowsocksrr/shadowsocks-rss/wiki/Subscribe-%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%A2%E9%98%85%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3

**Comment by shadowxr** [comment]
这是我解码他的，后面有=符号

修改一下，题主好想已经更新了，可以添加了


不过解码还是有=

成功添加原因不知

**Comment by j4Uq** [comment]
按照Wiki的规范改成ssr后面去掉=，订阅保留=，但是还是不能添加

**Comment by j4Uq** [comment]
ok了，我按照url safe base64的规范改了下脚本，手机可以正常订阅了，谢谢
