### ISSUE TITLE
安卓7.0下google play商店在分应用代理下无法连接到互联网

### ISSUE THREAD

**Issue by timwa0669** [shadowsocksrr/shadowsocksr-android#44]
如题，关闭分应用代理--全部正常，开启分应用代理同时分应用代理设置中代理所有程序--无法连接到互联网，设置中添加google账户也一样，这个bug偶尔不发作。
不知道是不是webview应用兼容的问题，这几个应用都使用了google webview

附上logcat
[logcat.log](https://github.com/shadowsocksrr/shadowsocksr-android/files/1495674/logcat.log)

~~ samsung rom api24

**Comment by nevesti** [comment]
不知道是不是webview应用兼容的问题，这几个应用都使用了google webview
