### ISSUE TITLE
我的手机关屏后程序会自动退出，用SS没这样的问题，大家有碰到吗？

### ISSUE THREAD

**Issue by vxyfv** [shadowsocksrr/shadowsocksr-android#47]
如题，后台有做了锁定，也加了白名单，设置允许后台运行，但关屏后程序还是会自动关掉，
每次都要重新打开，以前用SS没有发现这样的问题，我用的魅族手机。

**Comment by fishmacs** [comment]
我的一加三也是这样，安卓7

**Comment by Rogersunfly** [comment]
在手机settings- APP里面把关屏后app quit选项去掉

**Comment by Akkariiin** [comment]
应用信息->电池->锁屏后清理->Off

**Comment by vxyfv** [comment]
感谢大家的热心回复与帮助，我用的魅族手机，flyme系统，找了好久发现没这个选项。

**Comment by Akkariiin** [comment]
@xyf168 不同手机位置不一样，自己慢慢找

**Comment by marshmallow2333** [comment]
emmm，没发现

**Comment by Akkariiin** [comment]
@marshmallow2333 仔细找

**Comment by vxyfv** [comment]
@marshmallow2333 魅族是手机系统问题，工程师说是已经bug,还没修复。
