### ISSUE TITLE
扫描二维码镜头无法对焦问题

### ISSUE THREAD

**Issue by m4sop2** [shadowsocksrr/shadowsocksr-android#48]
使用二维码扫描的时候，图像特别模糊，几乎扫描不到，要很勉强才能扫描到，希望能够修复对焦问题。

**Comment by benqsr** [comment]
确实二维码扫描不好用

**Comment by AkaneAkaza** [comment]
自己安装外置版本

**Comment by Akkariiin** [comment]
自己装
https://play.google.com/store/apps/details?id=com.google.zxing.client.android
https://github.com/zxing/zxing/releases
