### ISSUE TITLE
新版混淆会添加tls1.2_ticket_fastauth支持么？

### ISSUE THREAD

**Issue by shadowxr** [shadowsocksrr/shadowsocksr-android#5]
我记得这个和tls1.2_ticket_auth可以互相支持
但是当选择tls1.2_ticket_fastauth，通过链接导入会识别错误显示为null，且无法直接改为tls1.2_ticket_auth。需要先更改为其他，才能更改为tls1.2_ticket_auth

**Comment by Akkariiin** [comment]
只有C#客户端支持tls1.2_ticket_fastauth

安卓遇到不支持或已经被删掉的就会自动变成null
