### ISSUE TITLE
无法添加订阅地址

### ISSUE THREAD

**Issue by ghost** [shadowsocksrr/shadowsocksr-android#54]
添加订阅地址之后一直显示处理中

**Comment by Akkariiin** [comment]
能提供更多细节吗？

**Comment by ghost** [comment]
打开软件，点加号  > 添加/升级SSR订阅 >添加订阅地址> xxxx.com/xxx.txt > 确定（实际上没有被添加，还是内置订阅地址）> 确定并升级（显示 处理中 请稍后）
我可以肯定的是我的订阅地址绝对没问题

**Comment by ghost** [comment]
我的安卓手机版本是7.1.2 lineageos14.1官方版本 。还有一部为lyme os 6的红米note2，安卓6.0
测试SSRR的版本分别为v3.5.1.1-alpha和v3.5.1，都无法正常添加订阅地址

**Comment by Qixingchen** [comment]
订阅内容格式错误 请确认你的订阅格式完全符合 https://github.com/ssrbackup/shadowsocks-rss/wiki/Subscribe-%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%A2%E9%98%85%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3

**Comment by ghost** [comment]
https://dzxs.github.io/hi.txt
https://raw.githubusercontent.com/shadowsocksrr/breakwa11.github.io/master/free/freenodeplain.txt
https://prom-php.herokuapp.com/cloudfra_ssr.txt
你自己用pc版的订阅这三个地址试试

**Comment by Qixingchen** [comment]
第一条格式错误 解码后ssr 地址不应带后缀等号，更别说是4个等号。
请参阅 https://github.com/ssrbackup/shadowsocks-rss/wiki/SSR-QRcode-scheme 
请不要以某个客户端可以识别作为验证依据

**Comment by ghost** [comment]
可是官方SSR4.7.0一版的确是可以订阅到第一条格式的，剩下两条格式SSRR可以订阅到

**Comment by osxn** [comment]
楼主解决了吗？遇上同样的问题

**Comment by soulloster** [comment]
和楼主的问题真提莫的一毛一样，感觉被政府针对了

**Comment by q847633684** [comment]
根域名不能订阅(如google.cn),子域名能订阅!(如www.google.cn)

**Comment by Star400633** [comment]
安装到电视上确实不能订阅   小米电视4  安卓6版本  输入好订阅地址后 点击确定  toast弹窗显示在处理中 然后弹窗消失  订阅列表中显示的还是默认的订阅名。
