### ISSUE TITLE
Android 8.1 中 WiFi 连接状态无法被识别

### ISSUE THREAD

**Issue by cccClyde** [shadowsocksrr/shadowsocksr-android#56]
Android 8.1 中开启 SSR/SS  后部分应用无法读取系统的 WiFi 连接状态。

具体表现为 WiFi 状态下 Google Photos 依然提示「等待 WiFi 备份」、Play 应用商店下载大型应用数据包前勾选「仅适用 WiFi 下载」后下载一直被挂起等等。

**Comment by Akkariiin** [comment]
有谁能提供更多信息吗？

**Comment by g5239277** [comment]
这个很多人怀疑是兼容性问题，具体原因未明，7.x无此问题。话说安卓版本很久没更新了。

**Comment by cccClyde** [comment]
Google 确认将在以后的版本里修复这个问题：https://issuetracker.google.com/issues/68956368，但具体是什么原因没说...

**Comment by cccClyde** [comment]
抱歉上面的地址有问题：https://issuetracker.google.com/issues/68956368

**Comment by Akkariiin** [comment]
@g5239277 https://github.com/shadowsocksrr/shadowsocksr-android/issues/55
