### ISSUE TITLE
耗电异常

### ISSUE THREAD

**Issue by PixelGe** [shadowsocksrr/shadowsocksr-android#60]
在Android8.0上特耗电

**Comment by Akkariiin** [comment]
有更多信息嘛？

**Comment by PixelGe** [comment]
Android 8.0 一加3t 后台一直挂ssr，耗电快

2017年12月22日 18:19，"Akkariiin" <notifications@github.com>写道：

**Comment by noncharacter** [comment]
估计是系统把所有走代理的应用电量消耗算到这个应用里了
