### ISSUE TITLE
安卓8.0无法添加订阅地址

### ISSUE THREAD

**Issue by heos2015** [shadowsocksrr/shadowsocksr-android#62]
安卓8.0无法添加订阅地址，安卓7.0的时候还可以多添加几次添加进去

**Comment by Akkariiin** [comment]
请参考 #54 检查一下是否是订阅地址本身的问题
或者可以换一个订阅地址试试看

我这里没有8.0的测试机，所以没有更多信息的情况下无法确定问题所在

**Comment by ghost** [comment]
表现为添加订阅地址后不正常的长时间的处理过后仍未出现在订阅列表中。

相同的订阅地址下：
Android 7.0 下 SSR 3.4.0.6；SSRR 3.5.1 都正常。
Android 8.0 下 SSR 3.4.0.6 正常；SSRR 3.5.1 不正常。

**Comment by Akkariiin** [comment]
不应该啊，SSRR应该只是编译环境变更了.

**Comment by heos2015** [comment]
修改了混淆和协议 能订阅啦 但是在安卓8.0下面经常提示后台刷新耗电 ，其它版本没这个提示，大神优化下吧

**Comment by heos2015** [comment]
准确的说应该是加密方式 换成chacha20就能添加

**Comment by Akkariiin** [comment]
耗电问题 #60

**Comment by LiZhanxiao** [comment]
把软件默认的订阅删掉
右滑删除
