### ISSUE TITLE
无法开机自启动

### ISSUE THREAD

**Issue by bydx** [shadowsocksrr/shadowsocksr-android#64]
SSRR 3.5.1.1，在放开所有权限的情况下无法实现开机自启动（同样条件下SSR 3.4.0.6也存在该问题，而Shadowsocks最新版正常），并且刚开机后点击shortcut「开关」毫无反应，除非进入程序连接一次后「开关」才能正常使用。
系统：Flyme 6.2，Android 5.1

**Comment by Etz-haChayim** [comment]
my s8 of sumsung is ok, it could autostart.

**Comment by Akkariiin** [comment]
自启动和关联启动的权限有打开吗？

**Comment by bydx** [comment]
@Akkariiin 自启动权限给了，关联启动Flyme5里有Flyme6找不到了。楼上有人说三星系统可以正常自启那看来就是Flyme的问题了，不过我觉得既然SS在Flyme6能自启SSRR应该也能搞定？哎
![s80125-191229](https://user-images.githubusercontent.com/31297910/35385951-1b93ef3e-0205-11e8-9bbd-45694b808e26.jpg)

**Comment by MichaelPan1026** [comment]
检查是否被黑域

**Comment by bydx** [comment]
@MichaelPanPRC 压根儿没用过黑域

**Comment by Akkariiin** [comment]
EMUI也可以自启动
后台管理那里，应该会有三个选项，分别是：开机自启动、后台运行、关联启动
