### ISSUE TITLE
[feature request] add xchacha20 to be compatible with server

### ISSUE THREAD

**Issue by kmahyyg** [shadowsocksrr/shadowsocksr-android#65]
Python server supported xchacha20.Then I upgraded my server.
Now, I found the 3.5.1 of Android Client doesn't have xchacha20 encrypt method.

Please add this feature.Thanks for your hard work.

**Comment by Akkariiin** [comment]
its a hard work and on doing now.

the xchacha20 dependent the crypto lib ```libsdium``` . but the shadowsocksr-libev 's libsdium are hard embed on the project with many modify.  it need many time to update the embeded lib to sync with newgest upsteam. and, the Android version direct run the libev to do the crypto operat.
so, this is a hard work , and need more time to do it.  please relax and wait. thanks...

and one of the temporary solution is that , config the server to run on two port, the one use xchacha20 which used by C#, and the another use chacha20 or chacha20-ietf which used by android.


[ the multi port config ](https://github.com/shadowsocksrr/shadowsocks-rss/wiki/config.json#%E5%A4%9A%E7%AB%AF%E5%8F%A3%E9%85%8D%E7%BD%AE)

**Comment by kmahyyg** [comment]
Thanks for your hard work.
