### ISSUE TITLE
安卓8.0下链接服务器工作几秒后失效

### ISSUE THREAD

**Issue by kaiyuandjw** [shadowsocksrr/shadowsocksr-android#67]
安卓8.0时链接到服务器后只能工作几秒，走一百多kb的数据，然后就没数据了，app显示连接正常，但是不走数据

**Comment by Akkariiin** [comment]
有更多信息吗？

**Comment by rhjdvsgsgks** [comment]
ssrr是否从电池优化名单中移除？

**Comment by kaiyuandjw** [comment]
已移除

2018-01-28 23:44 GMT+08:00 FCXplus <notifications@github.com>:

**Comment by KingdomRushK** [comment]
@Akkariiin 
我好像也遇到了类似问题，如有需要可以把log发去看看。

**Comment by chiau9** [comment]
我也一样啊，3.5.1.1版本，在我的小米6手机上，安卓奥利奥的。和你们情况一样，会断线。

**Comment by Akkariiin** [comment]
#77
