### ISSUE TITLE
期待加入负载均衡

### ISSUE THREAD

**Issue by ypj034** [shadowsocksrr/shadowsocksr-android#69]
觉得这个功能很好用，期待加入

**Comment by at-ease** [comment]
坚决支持

**Comment by birdofprey** [comment]
期待该功能。混淆功能也需要增强。。。1.熵增。2.低带宽数据率 希望有TARBALL下载地址提供。谢谢

**Comment by Akkariiin** [comment]
#11

**Comment by Akkariiin** [comment]
@birdofprey C#的TARBALL版，可以试试重编译一个linux版的libsscrypto并替换原始版本来解决本地图的问题，你可以试试
另外有关托盘菜单的功能也有可能出问题
我没有TARBALL的环境，你可以试试看
