### ISSUE TITLE
No way to remove profiles

### ISSUE THREAD

**Issue by kyeongsoo** [shadowsocksrr/shadowsocksr-android#72]
First of all, I do greatly appreciate this invaluable SW as one now working in China.

Due to increasing blockage of IP addresses by GFW, I have been constantly terminating blocked SSR servers (i.e., VPS) and creating new ones.

The current version (3.5.1.1) allows adding new profiles through "+" button on the bottom, but I couldn't figure out how to remove existing profiles at all.

It would be appreciated if you could advise me how to do or implement this feature (i.e., removing existing profiles) in the upcoming version when there is no such feature in the current version.

**Comment by rhjdvsgsgks** [comment]
swipe to remove

**Comment by kyeongsoo** [comment]
Oh I see. Great thanks!
