### ISSUE TITLE
请问一下安卓客户端的混淆方式问题

### ISSUE THREAD

**Issue by lcpp1123** [shadowsocksrr/shadowsocksr-android#83]
请问一下安卓客户端的混淆方式问题 发现最新的SSRR客户端只有tls 1.2_ticket_auth 而没有tls 1.2_ticket_fastauth  是什么情况？二者兼容吗？我服务端使用的是fastauth。

**Comment by lucas-fangl** [comment]
同问，我也是

**Comment by leonf-tech** [comment]
the same

**Comment by Akkariiin** [comment]
兼容

**Comment by Akkariiin** [comment]
Android使用的libev暂未实现fastauth
现在只有C#客户端实现了fastauth

**Comment by lcpp1123** [comment]
感谢！
