### ISSUE TITLE
关于SSRR版本更新问题

### ISSUE THREAD

**Issue by yyluxe** [shadowsocksrr/shadowsocksr-android#84]
以前别人传给我一个3.5.1.1版本的，想更新一下不知道怎么整

**Comment by benqsr** [comment]
没有发布的更新的版本

**Comment by yibin001** [comment]
直接传到手机安装啊

**Comment by mittervis** [comment]
https://github.com/shadowsocksrr/shadowsocksr-android/releases
在这边，不知道你还需不需要
