### ISSUE TITLE
升级原生8.1就一直有这个问题。

### ISSUE THREAD

**Issue by 1478976213** [shadowsocksrr/shadowsocksr-android#88]
[我7.1正常使用，另一个手机小米6。MIUI9。安卓8.0也正常。就是这备用机8.1无法正常使用，谁知道为什么？[
![img20180303200403](https://user-images.githubusercontent.com/32958832/36934136-be2aba16-1f1f-11e8-96df-43cb44b6fcdf.jpg)
](url)

**Comment by tinyXiongGG** [comment]
**我也出现了同样的问题**
PC版可以正常使用，安卓 8.1 失败
- 手机型号：一加5
- 安卓版本：8.1
- SSR 版本：3.4.0.8
检查网络连接的时候会提示失败
![_20180526172340](https://user-images.githubusercontent.com/25929833/40574720-a00923a2-6109-11e8-8e20-4f8f292fc179.jpg)
![_20180526172331](https://user-images.githubusercontent.com/25929833/40574721-a19355b2-6109-11e8-8df4-8ce7837eeef5.jpg)

**Comment by Akkariiin** [comment]
上面cannot run，这个是小米rom的问题，请更新到最新版

**Comment by Akkariiin** [comment]
下面这个是默认节点吧？默认节点现在好像不能用。
