### ISSUE TITLE
All SSR and SSRR versions FC without any prompt

### ISSUE THREAD

**Issue by CaKrome** [shadowsocksrr/shadowsocksr-android#9]
This seems quite weird, but it does happen on my phone( Xiaomi Redmi Note 4 MediaTek variant, nikel, AOSP 6.0).
After installed SSR or SSRR, when I tapped the icon on my launcher, the program interface will appear for a very short time(about 0.5s-2s), then it would forcibly closed for no reason, even no a prompt said the program has stopped. Interestingly a very unique SSR version works, but it wasn't developed by Breakwa11 nor Akkariiin, it's a version has a package name(net.htcp.shadowsocksr) and with a completely different GUI, more similar to original shadowsocks-android, also with a grey icon.
The description below is what I tried to fix that, but it couldn't work.
I used an app called Preferences Manager to modify the preferences of SSRR, and tried open TCP Fast Open, it couldn't work, and turned on NAT mode, it even caused my phone to reboot. That's quite weird.

**Comment by Akkariiin** [comment]
How puzzling it is.
it seems like a exception throwed. but i cannot know what and why without error log.

**Comment by CaKrome** [comment]
Sorry for didn't posting the error log...simply because I don't know how to get it.

**Comment by Akkariiin** [comment]
Yes, i known that.

get the log from a really android machine is a hard work, some machine cannot log anything , example , Huawei . but some issue happend on special machine.

so, i say that is a puzzling.

**Comment by CaKrome** [comment]
So I've done some investigation about this issue, finally the problem lies in my 3rd-party rom. The trick is here, MTK based phones basically have NO or minimum support ether from companies or communities. Because [MTK doesn't share their chips' kernel sources with phone factories](http://www.gizchina.com/2014/03/24/mediatek-dont-share-source-code/). If factories want to update their phones' android version, they have to PAY for that, while Qualcomm does it for free. And its also a violation of GPL.  Obviously every phone with MTK soc are hard to get support to fix bugs, just like Redmi Note 4 MTK, third-party AOSP roms all based on the buggy kernel, caused many problems ( e.g. poor NAT support ) Thus there is a high possibility which bug is in the rom, not in SSR(R) itself.
I've planned to sell that phone and switch to Snapdragon variant, and won't buy MTK based devices any more.
Anyway, thanks for your patient replies!

**Comment by Akkariiin** [comment]
oh, good luck for you ~
