### ISSUE TITLE
感觉SSR始终不是很稳定，如果可以开发一款类似于iOS端Surge的App就好了

### ISSUE THREAD

**Issue by seoho8908** [shadowsocksrr/shadowsocksr-android#93]
感觉SSR始终不是很稳定，如果可以开发一款类似于iOS端Surge的App就好了

@Akkariiin

**Comment by yibin001** [comment]
这个估计不大可能吧……

**Comment by Akkariiin** [comment]
架构不同，环境不同
安卓客户端不稳定很多情况下是环境导致的，而开发者只能适应和兼容各种不同的环境。

**Comment by Justsoos** [comment]
这不是瞎扯蛋么。surge 那东西根本就不是卖翻墙的，人家是什么全攻能网络工具，只不过作者来蹭了几次ss 和 ssr 热点事件营销，和功能稳定一毛钱关系没有。
而另外，surge 底层算法依然还是这些 ss 算法，与稳定有什么关系？ 相反，功能太多，才不见得稳定。
