### ISSUE TITLE
shadowsocksr-android怎么共享

### ISSUE THREAD

**Issue by lovese** [shadowsocksrr/shadowsocksr-android#97]
shadowsocksr-android怎么共享给局域网的人用？想电脑版shadowsocksr-win那样

**Comment by ncs19960831** [comment]
可以打开任何设备的代理接口输入http://ip:port 选择sock5的话直接输ip

**Comment by lovese** [comment]
@ncs19960831 没明白，我好像在shadowsocksr-android里没找到共享网络的选项

**Comment by ncs19960831** [comment]
很抱歉，貌似不可以

**Comment by Akkariiin** [comment]
https://github.com/shadowsocksrr/shadowsocksr-android/issues/10
