### ISSUE TITLE
内建扫码调用不了 总是要外部的

### ISSUE THREAD

**Issue by Feiyuyu0503** [shadowsocksrr/shadowsocksr-android#99]
小米6 miui9安卓8.0。 调用外部的二维码时 会让我选择用哪个app扫描 选择了一个作为默认 下一次还是要选择 有的app都不是扫码的 权限也给足了。

**Comment by Akkariiin** [comment]
这个是这些app监听了太多类型的请求，才会导致这样的问题，与SSRR使用的二维码扫描功能无关

**Comment by Akkariiin** [comment]
内建扫码只在没有任何外部扫码软件响应扫码请求时才会调用，因为内置扫码模块的可靠性不够高
